// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAttachRoleToUserParams creates a new AttachRoleToUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAttachRoleToUserParams() *AttachRoleToUserParams {
	return NewAttachRoleToUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewAttachRoleToUserParamsWithTimeout creates a new AttachRoleToUserParams object
// with the ability to set a timeout on a request.
func NewAttachRoleToUserParamsWithTimeout(timeout time.Duration) *AttachRoleToUserParams {
	return &AttachRoleToUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewAttachRoleToUserParamsWithContext creates a new AttachRoleToUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [AttachRoleToUserParams].
func NewAttachRoleToUserParamsWithContext(ctx context.Context) *AttachRoleToUserParams {
	return &AttachRoleToUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewAttachRoleToUserParamsWithHTTPClient creates a new AttachRoleToUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewAttachRoleToUserParamsWithHTTPClient(client *http.Client) *AttachRoleToUserParams {
	return &AttachRoleToUserParams{
		HTTPClient: client,
	}
}

/*
AttachRoleToUserParams contains all the parameters to send to the API endpoint

	for the attach role to user operation.

	Typically these are written to a http.Request.
*/
type AttachRoleToUserParams struct {

	/* Role.

	   Name of the role to attach. (Required)
	*/
	Role string

	/* UserID.

	   Username or email of the user. (Required)
	*/
	UserID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the attach role to user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachRoleToUserParams) WithDefaults() *AttachRoleToUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the attach role to user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachRoleToUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the attach role to user params.
func (o *AttachRoleToUserParams) WithTimeout(timeout time.Duration) *AttachRoleToUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attach role to user params.
func (o *AttachRoleToUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the attach role to user params.
//
// Deprecated: use the operation call with context to pass the context instead of [AttachRoleToUserParams].
func (o *AttachRoleToUserParams) WithContext(ctx context.Context) *AttachRoleToUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attach role to user params.
//
// Deprecated: use the operation call with context to pass the context instead of [AttachRoleToUserParams].
func (o *AttachRoleToUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the attach role to user params.
func (o *AttachRoleToUserParams) WithHTTPClient(client *http.Client) *AttachRoleToUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attach role to user params.
func (o *AttachRoleToUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the attach role to user params.
func (o *AttachRoleToUserParams) WithRole(role string) *AttachRoleToUserParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the attach role to user params.
func (o *AttachRoleToUserParams) SetRole(role string) {
	o.Role = role
}

// WithUserID adds the userID to the attach role to user params.
func (o *AttachRoleToUserParams) WithUserID(userID string) *AttachRoleToUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the attach role to user params.
func (o *AttachRoleToUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *AttachRoleToUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	// path param user-id
	if err := r.SetPathParam("user-id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
