// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateUserParams creates a new CreateUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateUserParams() *CreateUserParams {
	return NewCreateUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewCreateUserParamsWithTimeout creates a new CreateUserParams object
// with the ability to set a timeout on a request.
func NewCreateUserParamsWithTimeout(timeout time.Duration) *CreateUserParams {
	return &CreateUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewCreateUserParamsWithContext creates a new CreateUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateUserParams].
func NewCreateUserParamsWithContext(ctx context.Context) *CreateUserParams {
	return &CreateUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewCreateUserParamsWithHTTPClient creates a new CreateUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateUserParamsWithHTTPClient(client *http.Client) *CreateUserParams {
	return &CreateUserParams{
		HTTPClient: client,
	}
}

/*
CreateUserParams contains all the parameters to send to the API endpoint

	for the create user operation.

	Typically these are written to a http.Request.
*/
type CreateUserParams struct {

	/* Email.

	   Email address of the user (required).
	*/
	Email string

	/* Firstname.

	   First name of the user (required).
	*/
	Firstname *string

	/* Lastname.

	   Last name of the user (required).
	*/
	Lastname *string

	/* Password.

	   Password for the new user account (required).
	*/
	Password string

	/* Tags.

	   Set additional tags for the User (use key=value format, comma-separated).
	*/
	Tags *string

	/* Username.

	   Username for the new user account (required).
	*/
	Username string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the create user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserParams) WithDefaults() *CreateUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create user params.
func (o *CreateUserParams) WithTimeout(timeout time.Duration) *CreateUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create user params.
func (o *CreateUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the create user params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateUserParams].
func (o *CreateUserParams) WithContext(ctx context.Context) *CreateUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create user params.
//
// Deprecated: use the operation call with context to pass the context instead of [CreateUserParams].
func (o *CreateUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the create user params.
func (o *CreateUserParams) WithHTTPClient(client *http.Client) *CreateUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create user params.
func (o *CreateUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the create user params.
func (o *CreateUserParams) WithEmail(email string) *CreateUserParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the create user params.
func (o *CreateUserParams) SetEmail(email string) {
	o.Email = email
}

// WithFirstname adds the firstname to the create user params.
func (o *CreateUserParams) WithFirstname(firstname *string) *CreateUserParams {
	o.SetFirstname(firstname)
	return o
}

// SetFirstname adds the firstname to the create user params.
func (o *CreateUserParams) SetFirstname(firstname *string) {
	o.Firstname = firstname
}

// WithLastname adds the lastname to the create user params.
func (o *CreateUserParams) WithLastname(lastname *string) *CreateUserParams {
	o.SetLastname(lastname)
	return o
}

// SetLastname adds the lastname to the create user params.
func (o *CreateUserParams) SetLastname(lastname *string) {
	o.Lastname = lastname
}

// WithPassword adds the password to the create user params.
func (o *CreateUserParams) WithPassword(password string) *CreateUserParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the create user params.
func (o *CreateUserParams) SetPassword(password string) {
	o.Password = password
}

// WithTags adds the tags to the create user params.
func (o *CreateUserParams) WithTags(tags *string) *CreateUserParams {
	o.SetTags(tags)
	return o
}

// SetTags adds the tags to the create user params.
func (o *CreateUserParams) SetTags(tags *string) {
	o.Tags = tags
}

// WithUsername adds the username to the create user params.
func (o *CreateUserParams) WithUsername(username string) *CreateUserParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the create user params.
func (o *CreateUserParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *CreateUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// query param email
	qrEmail := o.Email
	qEmail := qrEmail
	if qEmail != "" {

		if err := r.SetQueryParam("email", qEmail); err != nil {
			return err
		}
	}

	if o.Firstname != nil {

		// query param firstname
		var qrFirstname string

		if o.Firstname != nil {
			qrFirstname = *o.Firstname
		}
		qFirstname := qrFirstname
		if qFirstname != "" {

			if err := r.SetQueryParam("firstname", qFirstname); err != nil {
				return err
			}
		}
	}

	if o.Lastname != nil {

		// query param lastname
		var qrLastname string

		if o.Lastname != nil {
			qrLastname = *o.Lastname
		}
		qLastname := qrLastname
		if qLastname != "" {

			if err := r.SetQueryParam("lastname", qLastname); err != nil {
				return err
			}
		}
	}

	// query param password
	qrPassword := o.Password
	qPassword := qrPassword
	if qPassword != "" {

		if err := r.SetQueryParam("password", qPassword); err != nil {
			return err
		}
	}

	if o.Tags != nil {

		// query param tags
		var qrTags string

		if o.Tags != nil {
			qrTags = *o.Tags
		}
		qTags := qrTags
		if qTags != "" {

			if err := r.SetQueryParam("tags", qTags); err != nil {
				return err
			}
		}
	}

	// query param username
	qrUsername := o.Username
	qUsername := qrUsername
	if qUsername != "" {

		if err := r.SetQueryParam("username", qUsername); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
