// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DeleteServiceAccountReader is a Reader for the DeleteServiceAccount structure.
type DeleteServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteServiceAccountAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteServiceAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteServiceAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteServiceAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteServiceAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteServiceAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /roles/service-accounts/{name}] deleteServiceAccount", response, response.Code())
	}
}

// NewDeleteServiceAccountAccepted creates a DeleteServiceAccountAccepted with default headers values
func NewDeleteServiceAccountAccepted() *DeleteServiceAccountAccepted {
	return &DeleteServiceAccountAccepted{}
}

/*
DeleteServiceAccountAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for Service Account deletion.
*/
type DeleteServiceAccountAccepted struct {
	Payload *DeleteServiceAccountAcceptedBody
}

// IsSuccess returns true when this delete service account accepted response has a 2xx status code
func (o *DeleteServiceAccountAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete service account accepted response has a 3xx status code
func (o *DeleteServiceAccountAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account accepted response has a 4xx status code
func (o *DeleteServiceAccountAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete service account accepted response has a 5xx status code
func (o *DeleteServiceAccountAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service account accepted response a status code equal to that given
func (o *DeleteServiceAccountAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete service account accepted response
func (o *DeleteServiceAccountAccepted) Code() int {
	return 202
}

func (o *DeleteServiceAccountAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountAccepted %s", 202, payload)
}

func (o *DeleteServiceAccountAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountAccepted %s", 202, payload)
}

func (o *DeleteServiceAccountAccepted) GetPayload() *DeleteServiceAccountAcceptedBody {
	return o.Payload
}

func (o *DeleteServiceAccountAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteServiceAccountAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteServiceAccountBadRequest creates a DeleteServiceAccountBadRequest with default headers values
func NewDeleteServiceAccountBadRequest() *DeleteServiceAccountBadRequest {
	return &DeleteServiceAccountBadRequest{}
}

/*
DeleteServiceAccountBadRequest describes a response with status code 400, with default header values.

Cannot delete a Service Account with active instance bindings (use detach first).
*/
type DeleteServiceAccountBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete service account bad request response has a 2xx status code
func (o *DeleteServiceAccountBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete service account bad request response has a 3xx status code
func (o *DeleteServiceAccountBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account bad request response has a 4xx status code
func (o *DeleteServiceAccountBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete service account bad request response has a 5xx status code
func (o *DeleteServiceAccountBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service account bad request response a status code equal to that given
func (o *DeleteServiceAccountBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete service account bad request response
func (o *DeleteServiceAccountBadRequest) Code() int {
	return 400
}

func (o *DeleteServiceAccountBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountBadRequest %s", 400, payload)
}

func (o *DeleteServiceAccountBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountBadRequest %s", 400, payload)
}

func (o *DeleteServiceAccountBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServiceAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteServiceAccountUnauthorized creates a DeleteServiceAccountUnauthorized with default headers values
func NewDeleteServiceAccountUnauthorized() *DeleteServiceAccountUnauthorized {
	return &DeleteServiceAccountUnauthorized{}
}

/*
DeleteServiceAccountUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type DeleteServiceAccountUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete service account unauthorized response has a 2xx status code
func (o *DeleteServiceAccountUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete service account unauthorized response has a 3xx status code
func (o *DeleteServiceAccountUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account unauthorized response has a 4xx status code
func (o *DeleteServiceAccountUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete service account unauthorized response has a 5xx status code
func (o *DeleteServiceAccountUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service account unauthorized response a status code equal to that given
func (o *DeleteServiceAccountUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete service account unauthorized response
func (o *DeleteServiceAccountUnauthorized) Code() int {
	return 401
}

func (o *DeleteServiceAccountUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountUnauthorized %s", 401, payload)
}

func (o *DeleteServiceAccountUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountUnauthorized %s", 401, payload)
}

func (o *DeleteServiceAccountUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServiceAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteServiceAccountForbidden creates a DeleteServiceAccountForbidden with default headers values
func NewDeleteServiceAccountForbidden() *DeleteServiceAccountForbidden {
	return &DeleteServiceAccountForbidden{}
}

/*
DeleteServiceAccountForbidden describes a response with status code 403, with default header values.

Insufficient permissions to delete Service Accounts. Only Owner can do this.
*/
type DeleteServiceAccountForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete service account forbidden response has a 2xx status code
func (o *DeleteServiceAccountForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete service account forbidden response has a 3xx status code
func (o *DeleteServiceAccountForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account forbidden response has a 4xx status code
func (o *DeleteServiceAccountForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete service account forbidden response has a 5xx status code
func (o *DeleteServiceAccountForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service account forbidden response a status code equal to that given
func (o *DeleteServiceAccountForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete service account forbidden response
func (o *DeleteServiceAccountForbidden) Code() int {
	return 403
}

func (o *DeleteServiceAccountForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountForbidden %s", 403, payload)
}

func (o *DeleteServiceAccountForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountForbidden %s", 403, payload)
}

func (o *DeleteServiceAccountForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServiceAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteServiceAccountNotFound creates a DeleteServiceAccountNotFound with default headers values
func NewDeleteServiceAccountNotFound() *DeleteServiceAccountNotFound {
	return &DeleteServiceAccountNotFound{}
}

/*
DeleteServiceAccountNotFound describes a response with status code 404, with default header values.

Service Account not found.
*/
type DeleteServiceAccountNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete service account not found response has a 2xx status code
func (o *DeleteServiceAccountNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete service account not found response has a 3xx status code
func (o *DeleteServiceAccountNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account not found response has a 4xx status code
func (o *DeleteServiceAccountNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete service account not found response has a 5xx status code
func (o *DeleteServiceAccountNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service account not found response a status code equal to that given
func (o *DeleteServiceAccountNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete service account not found response
func (o *DeleteServiceAccountNotFound) Code() int {
	return 404
}

func (o *DeleteServiceAccountNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountNotFound %s", 404, payload)
}

func (o *DeleteServiceAccountNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountNotFound %s", 404, payload)
}

func (o *DeleteServiceAccountNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServiceAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteServiceAccountInternalServerError creates a DeleteServiceAccountInternalServerError with default headers values
func NewDeleteServiceAccountInternalServerError() *DeleteServiceAccountInternalServerError {
	return &DeleteServiceAccountInternalServerError{}
}

/*
DeleteServiceAccountInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteServiceAccountInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete service account internal server error response has a 2xx status code
func (o *DeleteServiceAccountInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete service account internal server error response has a 3xx status code
func (o *DeleteServiceAccountInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service account internal server error response has a 4xx status code
func (o *DeleteServiceAccountInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete service account internal server error response has a 5xx status code
func (o *DeleteServiceAccountInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete service account internal server error response a status code equal to that given
func (o *DeleteServiceAccountInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete service account internal server error response
func (o *DeleteServiceAccountInternalServerError) Code() int {
	return 500
}

func (o *DeleteServiceAccountInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountInternalServerError %s", 500, payload)
}

func (o *DeleteServiceAccountInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/service-accounts/{name}][%d] deleteServiceAccountInternalServerError %s", 500, payload)
}

func (o *DeleteServiceAccountInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteServiceAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteServiceAccountAcceptedBody delete service account accepted body
swagger:model DeleteServiceAccountAcceptedBody
*/
type DeleteServiceAccountAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this delete service account accepted body
func (o *DeleteServiceAccountAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteServiceAccountAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteServiceAccountAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var deleteServiceAccountAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteServiceAccountAcceptedBodyTypeStatusPropEnum = append(deleteServiceAccountAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteServiceAccountAcceptedBodyStatusAccepted captures enum value "accepted"
	DeleteServiceAccountAcceptedBodyStatusAccepted string = "accepted"

	// DeleteServiceAccountAcceptedBodyStatusCompleted captures enum value "completed"
	DeleteServiceAccountAcceptedBodyStatusCompleted string = "completed"

	// DeleteServiceAccountAcceptedBodyStatusFailed captures enum value "failed"
	DeleteServiceAccountAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DeleteServiceAccountAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteServiceAccountAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteServiceAccountAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("deleteServiceAccountAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DeleteServiceAccountAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteServiceAccountAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete service account accepted body based on context it is used
func (o *DeleteServiceAccountAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteServiceAccountAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteServiceAccountAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DeleteServiceAccountAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
