// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTenantParams creates a new DeleteTenantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTenantParams() *DeleteTenantParams {
	return NewDeleteTenantParamsWithTimeout(cr.DefaultTimeout)
}

// NewDeleteTenantParamsWithTimeout creates a new DeleteTenantParams object
// with the ability to set a timeout on a request.
func NewDeleteTenantParamsWithTimeout(timeout time.Duration) *DeleteTenantParams {
	return &DeleteTenantParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDeleteTenantParamsWithContext creates a new DeleteTenantParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteTenantParams].
func NewDeleteTenantParamsWithContext(ctx context.Context) *DeleteTenantParams {
	return &DeleteTenantParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDeleteTenantParamsWithHTTPClient creates a new DeleteTenantParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTenantParamsWithHTTPClient(client *http.Client) *DeleteTenantParams {
	return &DeleteTenantParams{
		HTTPClient: client,
	}
}

/*
DeleteTenantParams contains all the parameters to send to the API endpoint

	for the delete tenant operation.

	Typically these are written to a http.Request.
*/
type DeleteTenantParams struct {

	/* TenantID.

	   Unique ID of the tenant to be deleted (required).
	*/
	TenantID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the delete tenant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTenantParams) WithDefaults() *DeleteTenantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete tenant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTenantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete tenant params.
func (o *DeleteTenantParams) WithTimeout(timeout time.Duration) *DeleteTenantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete tenant params.
func (o *DeleteTenantParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the delete tenant params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteTenantParams].
func (o *DeleteTenantParams) WithContext(ctx context.Context) *DeleteTenantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete tenant params.
//
// Deprecated: use the operation call with context to pass the context instead of [DeleteTenantParams].
func (o *DeleteTenantParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the delete tenant params.
func (o *DeleteTenantParams) WithHTTPClient(client *http.Client) *DeleteTenantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete tenant params.
func (o *DeleteTenantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the delete tenant params.
func (o *DeleteTenantParams) WithTenantID(tenantID string) *DeleteTenantParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete tenant params.
func (o *DeleteTenantParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DeleteTenantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenant-id
	if err := r.SetPathParam("tenant-id", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
