// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DeleteVolumeSnapshotReader is a Reader for the DeleteVolumeSnapshot structure.
type DeleteVolumeSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVolumeSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteVolumeSnapshotAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteVolumeSnapshotBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /compute/volumes/snapshots/{snapshot-id}] deleteVolumeSnapshot", response, response.Code())
	}
}

// NewDeleteVolumeSnapshotAccepted creates a DeleteVolumeSnapshotAccepted with default headers values
func NewDeleteVolumeSnapshotAccepted() *DeleteVolumeSnapshotAccepted {
	return &DeleteVolumeSnapshotAccepted{}
}

/*
DeleteVolumeSnapshotAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for deleting volume snapshot
*/
type DeleteVolumeSnapshotAccepted struct {
	Payload *DeleteVolumeSnapshotAcceptedBody
}

// IsSuccess returns true when this delete volume snapshot accepted response has a 2xx status code
func (o *DeleteVolumeSnapshotAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete volume snapshot accepted response has a 3xx status code
func (o *DeleteVolumeSnapshotAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete volume snapshot accepted response has a 4xx status code
func (o *DeleteVolumeSnapshotAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete volume snapshot accepted response has a 5xx status code
func (o *DeleteVolumeSnapshotAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete volume snapshot accepted response a status code equal to that given
func (o *DeleteVolumeSnapshotAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete volume snapshot accepted response
func (o *DeleteVolumeSnapshotAccepted) Code() int {
	return 202
}

func (o *DeleteVolumeSnapshotAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/snapshots/{snapshot-id}][%d] deleteVolumeSnapshotAccepted %s", 202, payload)
}

func (o *DeleteVolumeSnapshotAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/snapshots/{snapshot-id}][%d] deleteVolumeSnapshotAccepted %s", 202, payload)
}

func (o *DeleteVolumeSnapshotAccepted) GetPayload() *DeleteVolumeSnapshotAcceptedBody {
	return o.Payload
}

func (o *DeleteVolumeSnapshotAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteVolumeSnapshotAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteVolumeSnapshotBadRequest creates a DeleteVolumeSnapshotBadRequest with default headers values
func NewDeleteVolumeSnapshotBadRequest() *DeleteVolumeSnapshotBadRequest {
	return &DeleteVolumeSnapshotBadRequest{}
}

/*
DeleteVolumeSnapshotBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DeleteVolumeSnapshotBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete volume snapshot bad request response has a 2xx status code
func (o *DeleteVolumeSnapshotBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete volume snapshot bad request response has a 3xx status code
func (o *DeleteVolumeSnapshotBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete volume snapshot bad request response has a 4xx status code
func (o *DeleteVolumeSnapshotBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete volume snapshot bad request response has a 5xx status code
func (o *DeleteVolumeSnapshotBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete volume snapshot bad request response a status code equal to that given
func (o *DeleteVolumeSnapshotBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete volume snapshot bad request response
func (o *DeleteVolumeSnapshotBadRequest) Code() int {
	return 400
}

func (o *DeleteVolumeSnapshotBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/snapshots/{snapshot-id}][%d] deleteVolumeSnapshotBadRequest %s", 400, payload)
}

func (o *DeleteVolumeSnapshotBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/snapshots/{snapshot-id}][%d] deleteVolumeSnapshotBadRequest %s", 400, payload)
}

func (o *DeleteVolumeSnapshotBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVolumeSnapshotBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteVolumeSnapshotAcceptedBody delete volume snapshot accepted body
swagger:model DeleteVolumeSnapshotAcceptedBody
*/
type DeleteVolumeSnapshotAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this delete volume snapshot accepted body
func (o *DeleteVolumeSnapshotAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVolumeSnapshotAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteVolumeSnapshotAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var deleteVolumeSnapshotAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteVolumeSnapshotAcceptedBodyTypeStatusPropEnum = append(deleteVolumeSnapshotAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteVolumeSnapshotAcceptedBodyStatusAccepted captures enum value "accepted"
	DeleteVolumeSnapshotAcceptedBodyStatusAccepted string = "accepted"

	// DeleteVolumeSnapshotAcceptedBodyStatusCompleted captures enum value "completed"
	DeleteVolumeSnapshotAcceptedBodyStatusCompleted string = "completed"

	// DeleteVolumeSnapshotAcceptedBodyStatusFailed captures enum value "failed"
	DeleteVolumeSnapshotAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DeleteVolumeSnapshotAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteVolumeSnapshotAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteVolumeSnapshotAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("deleteVolumeSnapshotAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DeleteVolumeSnapshotAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteVolumeSnapshotAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete volume snapshot accepted body based on context it is used
func (o *DeleteVolumeSnapshotAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteVolumeSnapshotAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteVolumeSnapshotAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DeleteVolumeSnapshotAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
