// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DeleteTenantReader is a Reader for the DeleteTenant structure.
type DeleteTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteTenantAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTenantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /tenants/{tenant-id}] deleteTenant", response, response.Code())
	}
}

// NewDeleteTenantAccepted creates a DeleteTenantAccepted with default headers values
func NewDeleteTenantAccepted() *DeleteTenantAccepted {
	return &DeleteTenantAccepted{}
}

/*
DeleteTenantAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for tenant deletion
*/
type DeleteTenantAccepted struct {
	Payload *DeleteTenantAcceptedBody
}

// IsSuccess returns true when this delete tenant accepted response has a 2xx status code
func (o *DeleteTenantAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete tenant accepted response has a 3xx status code
func (o *DeleteTenantAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tenant accepted response has a 4xx status code
func (o *DeleteTenantAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete tenant accepted response has a 5xx status code
func (o *DeleteTenantAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tenant accepted response a status code equal to that given
func (o *DeleteTenantAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete tenant accepted response
func (o *DeleteTenantAccepted) Code() int {
	return 202
}

func (o *DeleteTenantAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tenants/{tenant-id}][%d] deleteTenantAccepted %s", 202, payload)
}

func (o *DeleteTenantAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tenants/{tenant-id}][%d] deleteTenantAccepted %s", 202, payload)
}

func (o *DeleteTenantAccepted) GetPayload() *DeleteTenantAcceptedBody {
	return o.Payload
}

func (o *DeleteTenantAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteTenantAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTenantBadRequest creates a DeleteTenantBadRequest with default headers values
func NewDeleteTenantBadRequest() *DeleteTenantBadRequest {
	return &DeleteTenantBadRequest{}
}

/*
DeleteTenantBadRequest describes a response with status code 400, with default header values.

Invalid request due to incorrect tenant details or malformed request.
*/
type DeleteTenantBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete tenant bad request response has a 2xx status code
func (o *DeleteTenantBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete tenant bad request response has a 3xx status code
func (o *DeleteTenantBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tenant bad request response has a 4xx status code
func (o *DeleteTenantBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete tenant bad request response has a 5xx status code
func (o *DeleteTenantBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tenant bad request response a status code equal to that given
func (o *DeleteTenantBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete tenant bad request response
func (o *DeleteTenantBadRequest) Code() int {
	return 400
}

func (o *DeleteTenantBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tenants/{tenant-id}][%d] deleteTenantBadRequest %s", 400, payload)
}

func (o *DeleteTenantBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tenants/{tenant-id}][%d] deleteTenantBadRequest %s", 400, payload)
}

func (o *DeleteTenantBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteTenantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteTenantAcceptedBody delete tenant accepted body
swagger:model DeleteTenantAcceptedBody
*/
type DeleteTenantAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this delete tenant accepted body
func (o *DeleteTenantAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteTenantAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteTenantAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var deleteTenantAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteTenantAcceptedBodyTypeStatusPropEnum = append(deleteTenantAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteTenantAcceptedBodyStatusAccepted captures enum value "accepted"
	DeleteTenantAcceptedBodyStatusAccepted string = "accepted"

	// DeleteTenantAcceptedBodyStatusCompleted captures enum value "completed"
	DeleteTenantAcceptedBodyStatusCompleted string = "completed"

	// DeleteTenantAcceptedBodyStatusFailed captures enum value "failed"
	DeleteTenantAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DeleteTenantAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteTenantAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteTenantAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("deleteTenantAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DeleteTenantAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteTenantAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete tenant accepted body based on context it is used
func (o *DeleteTenantAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteTenantAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteTenantAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DeleteTenantAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
