// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DeleteRoleReader is a Reader for the DeleteRole structure.
type DeleteRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteRoleAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteRoleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /roles/{name}] deleteRole", response, response.Code())
	}
}

// NewDeleteRoleAccepted creates a DeleteRoleAccepted with default headers values
func NewDeleteRoleAccepted() *DeleteRoleAccepted {
	return &DeleteRoleAccepted{}
}

/*
DeleteRoleAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for role deletion.
*/
type DeleteRoleAccepted struct {
	Payload *DeleteRoleAcceptedBody
}

// IsSuccess returns true when this delete role accepted response has a 2xx status code
func (o *DeleteRoleAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete role accepted response has a 3xx status code
func (o *DeleteRoleAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role accepted response has a 4xx status code
func (o *DeleteRoleAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete role accepted response has a 5xx status code
func (o *DeleteRoleAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete role accepted response a status code equal to that given
func (o *DeleteRoleAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete role accepted response
func (o *DeleteRoleAccepted) Code() int {
	return 202
}

func (o *DeleteRoleAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleAccepted %s", 202, payload)
}

func (o *DeleteRoleAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleAccepted %s", 202, payload)
}

func (o *DeleteRoleAccepted) GetPayload() *DeleteRoleAcceptedBody {
	return o.Payload
}

func (o *DeleteRoleAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteRoleAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRoleBadRequest creates a DeleteRoleBadRequest with default headers values
func NewDeleteRoleBadRequest() *DeleteRoleBadRequest {
	return &DeleteRoleBadRequest{}
}

/*
DeleteRoleBadRequest describes a response with status code 400, with default header values.

Cannot delete predefined roles or role is still referenced.
*/
type DeleteRoleBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete role bad request response has a 2xx status code
func (o *DeleteRoleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete role bad request response has a 3xx status code
func (o *DeleteRoleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role bad request response has a 4xx status code
func (o *DeleteRoleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete role bad request response has a 5xx status code
func (o *DeleteRoleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete role bad request response a status code equal to that given
func (o *DeleteRoleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete role bad request response
func (o *DeleteRoleBadRequest) Code() int {
	return 400
}

func (o *DeleteRoleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleBadRequest %s", 400, payload)
}

func (o *DeleteRoleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleBadRequest %s", 400, payload)
}

func (o *DeleteRoleBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRoleUnauthorized creates a DeleteRoleUnauthorized with default headers values
func NewDeleteRoleUnauthorized() *DeleteRoleUnauthorized {
	return &DeleteRoleUnauthorized{}
}

/*
DeleteRoleUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type DeleteRoleUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete role unauthorized response has a 2xx status code
func (o *DeleteRoleUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete role unauthorized response has a 3xx status code
func (o *DeleteRoleUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role unauthorized response has a 4xx status code
func (o *DeleteRoleUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete role unauthorized response has a 5xx status code
func (o *DeleteRoleUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete role unauthorized response a status code equal to that given
func (o *DeleteRoleUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete role unauthorized response
func (o *DeleteRoleUnauthorized) Code() int {
	return 401
}

func (o *DeleteRoleUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleUnauthorized %s", 401, payload)
}

func (o *DeleteRoleUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleUnauthorized %s", 401, payload)
}

func (o *DeleteRoleUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRoleForbidden creates a DeleteRoleForbidden with default headers values
func NewDeleteRoleForbidden() *DeleteRoleForbidden {
	return &DeleteRoleForbidden{}
}

/*
DeleteRoleForbidden describes a response with status code 403, with default header values.

Insufficient permissions. Only Owner can delete roles.
*/
type DeleteRoleForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete role forbidden response has a 2xx status code
func (o *DeleteRoleForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete role forbidden response has a 3xx status code
func (o *DeleteRoleForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role forbidden response has a 4xx status code
func (o *DeleteRoleForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete role forbidden response has a 5xx status code
func (o *DeleteRoleForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete role forbidden response a status code equal to that given
func (o *DeleteRoleForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete role forbidden response
func (o *DeleteRoleForbidden) Code() int {
	return 403
}

func (o *DeleteRoleForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleForbidden %s", 403, payload)
}

func (o *DeleteRoleForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleForbidden %s", 403, payload)
}

func (o *DeleteRoleForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRoleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRoleNotFound creates a DeleteRoleNotFound with default headers values
func NewDeleteRoleNotFound() *DeleteRoleNotFound {
	return &DeleteRoleNotFound{}
}

/*
DeleteRoleNotFound describes a response with status code 404, with default header values.

Role not found.
*/
type DeleteRoleNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete role not found response has a 2xx status code
func (o *DeleteRoleNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete role not found response has a 3xx status code
func (o *DeleteRoleNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role not found response has a 4xx status code
func (o *DeleteRoleNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete role not found response has a 5xx status code
func (o *DeleteRoleNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete role not found response a status code equal to that given
func (o *DeleteRoleNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete role not found response
func (o *DeleteRoleNotFound) Code() int {
	return 404
}

func (o *DeleteRoleNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleNotFound %s", 404, payload)
}

func (o *DeleteRoleNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleNotFound %s", 404, payload)
}

func (o *DeleteRoleNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteRoleInternalServerError creates a DeleteRoleInternalServerError with default headers values
func NewDeleteRoleInternalServerError() *DeleteRoleInternalServerError {
	return &DeleteRoleInternalServerError{}
}

/*
DeleteRoleInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteRoleInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete role internal server error response has a 2xx status code
func (o *DeleteRoleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete role internal server error response has a 3xx status code
func (o *DeleteRoleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete role internal server error response has a 4xx status code
func (o *DeleteRoleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete role internal server error response has a 5xx status code
func (o *DeleteRoleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete role internal server error response a status code equal to that given
func (o *DeleteRoleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete role internal server error response
func (o *DeleteRoleInternalServerError) Code() int {
	return 500
}

func (o *DeleteRoleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleInternalServerError %s", 500, payload)
}

func (o *DeleteRoleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /roles/{name}][%d] deleteRoleInternalServerError %s", 500, payload)
}

func (o *DeleteRoleInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteRoleAcceptedBody delete role accepted body
swagger:model DeleteRoleAcceptedBody
*/
type DeleteRoleAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this delete role accepted body
func (o *DeleteRoleAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteRoleAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteRoleAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var deleteRoleAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteRoleAcceptedBodyTypeStatusPropEnum = append(deleteRoleAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteRoleAcceptedBodyStatusAccepted captures enum value "accepted"
	DeleteRoleAcceptedBodyStatusAccepted string = "accepted"

	// DeleteRoleAcceptedBodyStatusCompleted captures enum value "completed"
	DeleteRoleAcceptedBodyStatusCompleted string = "completed"

	// DeleteRoleAcceptedBodyStatusFailed captures enum value "failed"
	DeleteRoleAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DeleteRoleAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteRoleAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteRoleAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("deleteRoleAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DeleteRoleAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteRoleAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete role accepted body based on context it is used
func (o *DeleteRoleAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteRoleAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteRoleAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DeleteRoleAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
