// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DeleteVolumeReader is a Reader for the DeleteVolume structure.
type DeleteVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteVolumeAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteVolumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /compute/volumes/{volume-id}] deleteVolume", response, response.Code())
	}
}

// NewDeleteVolumeAccepted creates a DeleteVolumeAccepted with default headers values
func NewDeleteVolumeAccepted() *DeleteVolumeAccepted {
	return &DeleteVolumeAccepted{}
}

/*
DeleteVolumeAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for volume deletion
*/
type DeleteVolumeAccepted struct {
	Payload *DeleteVolumeAcceptedBody
}

// IsSuccess returns true when this delete volume accepted response has a 2xx status code
func (o *DeleteVolumeAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete volume accepted response has a 3xx status code
func (o *DeleteVolumeAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete volume accepted response has a 4xx status code
func (o *DeleteVolumeAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete volume accepted response has a 5xx status code
func (o *DeleteVolumeAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this delete volume accepted response a status code equal to that given
func (o *DeleteVolumeAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the delete volume accepted response
func (o *DeleteVolumeAccepted) Code() int {
	return 202
}

func (o *DeleteVolumeAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/{volume-id}][%d] deleteVolumeAccepted %s", 202, payload)
}

func (o *DeleteVolumeAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/{volume-id}][%d] deleteVolumeAccepted %s", 202, payload)
}

func (o *DeleteVolumeAccepted) GetPayload() *DeleteVolumeAcceptedBody {
	return o.Payload
}

func (o *DeleteVolumeAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteVolumeAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteVolumeBadRequest creates a DeleteVolumeBadRequest with default headers values
func NewDeleteVolumeBadRequest() *DeleteVolumeBadRequest {
	return &DeleteVolumeBadRequest{}
}

/*
DeleteVolumeBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DeleteVolumeBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete volume bad request response has a 2xx status code
func (o *DeleteVolumeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete volume bad request response has a 3xx status code
func (o *DeleteVolumeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete volume bad request response has a 4xx status code
func (o *DeleteVolumeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete volume bad request response has a 5xx status code
func (o *DeleteVolumeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete volume bad request response a status code equal to that given
func (o *DeleteVolumeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete volume bad request response
func (o *DeleteVolumeBadRequest) Code() int {
	return 400
}

func (o *DeleteVolumeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/{volume-id}][%d] deleteVolumeBadRequest %s", 400, payload)
}

func (o *DeleteVolumeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /compute/volumes/{volume-id}][%d] deleteVolumeBadRequest %s", 400, payload)
}

func (o *DeleteVolumeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVolumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteVolumeAcceptedBody delete volume accepted body
swagger:model DeleteVolumeAcceptedBody
*/
type DeleteVolumeAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this delete volume accepted body
func (o *DeleteVolumeAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVolumeAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteVolumeAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var deleteVolumeAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deleteVolumeAcceptedBodyTypeStatusPropEnum = append(deleteVolumeAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DeleteVolumeAcceptedBodyStatusAccepted captures enum value "accepted"
	DeleteVolumeAcceptedBodyStatusAccepted string = "accepted"

	// DeleteVolumeAcceptedBodyStatusCompleted captures enum value "completed"
	DeleteVolumeAcceptedBodyStatusCompleted string = "completed"

	// DeleteVolumeAcceptedBodyStatusFailed captures enum value "failed"
	DeleteVolumeAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DeleteVolumeAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deleteVolumeAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DeleteVolumeAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("deleteVolumeAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DeleteVolumeAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("deleteVolumeAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete volume accepted body based on context it is used
func (o *DeleteVolumeAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteVolumeAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteVolumeAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DeleteVolumeAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
