// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DescribeTaskReader is a Reader for the DescribeTask structure.
type DescribeTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeTaskBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDescribeTaskUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDescribeTaskNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDescribeTaskInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tasks/{task-id}] describeTask", response, response.Code())
	}
}

// NewDescribeTaskOK creates a DescribeTaskOK with default headers values
func NewDescribeTaskOK() *DescribeTaskOK {
	return &DescribeTaskOK{}
}

/*
DescribeTaskOK describes a response with status code 200, with default header values.

Successful response with task details
*/
type DescribeTaskOK struct {
	Payload *DescribeTaskOKBody
}

// IsSuccess returns true when this describe task o k response has a 2xx status code
func (o *DescribeTaskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this describe task o k response has a 3xx status code
func (o *DescribeTaskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe task o k response has a 4xx status code
func (o *DescribeTaskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe task o k response has a 5xx status code
func (o *DescribeTaskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this describe task o k response a status code equal to that given
func (o *DescribeTaskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the describe task o k response
func (o *DescribeTaskOK) Code() int {
	return 200
}

func (o *DescribeTaskOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskOK %s", 200, payload)
}

func (o *DescribeTaskOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskOK %s", 200, payload)
}

func (o *DescribeTaskOK) GetPayload() *DescribeTaskOKBody {
	return o.Payload
}

func (o *DescribeTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DescribeTaskOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeTaskBadRequest creates a DescribeTaskBadRequest with default headers values
func NewDescribeTaskBadRequest() *DescribeTaskBadRequest {
	return &DescribeTaskBadRequest{}
}

/*
DescribeTaskBadRequest describes a response with status code 400, with default header values.

Invalid task ID provided
*/
type DescribeTaskBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe task bad request response has a 2xx status code
func (o *DescribeTaskBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe task bad request response has a 3xx status code
func (o *DescribeTaskBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe task bad request response has a 4xx status code
func (o *DescribeTaskBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe task bad request response has a 5xx status code
func (o *DescribeTaskBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this describe task bad request response a status code equal to that given
func (o *DescribeTaskBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the describe task bad request response
func (o *DescribeTaskBadRequest) Code() int {
	return 400
}

func (o *DescribeTaskBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskBadRequest %s", 400, payload)
}

func (o *DescribeTaskBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskBadRequest %s", 400, payload)
}

func (o *DescribeTaskBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeTaskBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeTaskUnauthorized creates a DescribeTaskUnauthorized with default headers values
func NewDescribeTaskUnauthorized() *DescribeTaskUnauthorized {
	return &DescribeTaskUnauthorized{}
}

/*
DescribeTaskUnauthorized describes a response with status code 401, with default header values.

Incorrect username or password
*/
type DescribeTaskUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe task unauthorized response has a 2xx status code
func (o *DescribeTaskUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe task unauthorized response has a 3xx status code
func (o *DescribeTaskUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe task unauthorized response has a 4xx status code
func (o *DescribeTaskUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe task unauthorized response has a 5xx status code
func (o *DescribeTaskUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this describe task unauthorized response a status code equal to that given
func (o *DescribeTaskUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the describe task unauthorized response
func (o *DescribeTaskUnauthorized) Code() int {
	return 401
}

func (o *DescribeTaskUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskUnauthorized %s", 401, payload)
}

func (o *DescribeTaskUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskUnauthorized %s", 401, payload)
}

func (o *DescribeTaskUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeTaskUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeTaskNotFound creates a DescribeTaskNotFound with default headers values
func NewDescribeTaskNotFound() *DescribeTaskNotFound {
	return &DescribeTaskNotFound{}
}

/*
DescribeTaskNotFound describes a response with status code 404, with default header values.

Task not found
*/
type DescribeTaskNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe task not found response has a 2xx status code
func (o *DescribeTaskNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe task not found response has a 3xx status code
func (o *DescribeTaskNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe task not found response has a 4xx status code
func (o *DescribeTaskNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe task not found response has a 5xx status code
func (o *DescribeTaskNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this describe task not found response a status code equal to that given
func (o *DescribeTaskNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the describe task not found response
func (o *DescribeTaskNotFound) Code() int {
	return 404
}

func (o *DescribeTaskNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskNotFound %s", 404, payload)
}

func (o *DescribeTaskNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskNotFound %s", 404, payload)
}

func (o *DescribeTaskNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeTaskNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeTaskInternalServerError creates a DescribeTaskInternalServerError with default headers values
func NewDescribeTaskInternalServerError() *DescribeTaskInternalServerError {
	return &DescribeTaskInternalServerError{}
}

/*
DescribeTaskInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DescribeTaskInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe task internal server error response has a 2xx status code
func (o *DescribeTaskInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe task internal server error response has a 3xx status code
func (o *DescribeTaskInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe task internal server error response has a 4xx status code
func (o *DescribeTaskInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe task internal server error response has a 5xx status code
func (o *DescribeTaskInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this describe task internal server error response a status code equal to that given
func (o *DescribeTaskInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the describe task internal server error response
func (o *DescribeTaskInternalServerError) Code() int {
	return 500
}

func (o *DescribeTaskInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskInternalServerError %s", 500, payload)
}

func (o *DescribeTaskInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tasks/{task-id}][%d] describeTaskInternalServerError %s", 500, payload)
}

func (o *DescribeTaskInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeTaskInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DescribeTaskOKBody describe task o k body
swagger:model DescribeTaskOKBody
*/
type DescribeTaskOKBody struct {

	// The timestamp when the task was created, in RFC3339 format.
	// Example: 0001-01-01T00:00:00Z
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// An error message if an error occurred during the task.
	// Example: error occurred
	ErrMessage string `json:"err_message,omitempty"`

	// Display task output data
	Output string `json:"output,omitempty"`

	// The current status of the task.
	// Example: completed
	Status string `json:"status,omitempty"`

	// The unique identifier for the task.
	// Example: e7b83174-deaf-497c-adb8-c616fc050ede
	TaskID string `json:"task-id,omitempty"`

	// The title or name of the task.
	// Example: vm_create
	Title string `json:"title,omitempty"`

	// The timestamp when the task was last updated, in RFC3339 format.
	// Example: 0001-01-01T00:00:00Z
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this describe task o k body
func (o *DescribeTaskOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeTaskOKBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("describeTaskOK"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *DescribeTaskOKBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("describeTaskOK"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this describe task o k body based on context it is used
func (o *DescribeTaskOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DescribeTaskOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DescribeTaskOKBody) UnmarshalBinary(b []byte) error {
	var res DescribeTaskOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
