// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeVolumeParams creates a new DescribeVolumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeVolumeParams() *DescribeVolumeParams {
	return NewDescribeVolumeParamsWithTimeout(cr.DefaultTimeout)
}

// NewDescribeVolumeParamsWithTimeout creates a new DescribeVolumeParams object
// with the ability to set a timeout on a request.
func NewDescribeVolumeParamsWithTimeout(timeout time.Duration) *DescribeVolumeParams {
	return &DescribeVolumeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDescribeVolumeParamsWithContext creates a new DescribeVolumeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVolumeParams].
func NewDescribeVolumeParamsWithContext(ctx context.Context) *DescribeVolumeParams {
	return &DescribeVolumeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDescribeVolumeParamsWithHTTPClient creates a new DescribeVolumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeVolumeParamsWithHTTPClient(client *http.Client) *DescribeVolumeParams {
	return &DescribeVolumeParams{
		HTTPClient: client,
	}
}

/*
DescribeVolumeParams contains all the parameters to send to the API endpoint

	for the describe volume operation.

	Typically these are written to a http.Request.
*/
type DescribeVolumeParams struct {

	/* VolumeID.

	   Specify the unique identifier of the volume. (Required)
	*/
	VolumeID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the describe volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeVolumeParams) WithDefaults() *DescribeVolumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeVolumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe volume params.
func (o *DescribeVolumeParams) WithTimeout(timeout time.Duration) *DescribeVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe volume params.
func (o *DescribeVolumeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the describe volume params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVolumeParams].
func (o *DescribeVolumeParams) WithContext(ctx context.Context) *DescribeVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe volume params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVolumeParams].
func (o *DescribeVolumeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the describe volume params.
func (o *DescribeVolumeParams) WithHTTPClient(client *http.Client) *DescribeVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe volume params.
func (o *DescribeVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVolumeID adds the volumeID to the describe volume params.
func (o *DescribeVolumeParams) WithVolumeID(volumeID string) *DescribeVolumeParams {
	o.SetVolumeID(volumeID)
	return o
}

// SetVolumeID adds the volumeId to the describe volume params.
func (o *DescribeVolumeParams) SetVolumeID(volumeID string) {
	o.VolumeID = volumeID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DescribeVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param volume-id
	if err := r.SetPathParam("volume-id", o.VolumeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
