// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DescribeUserReader is a Reader for the DescribeUser structure.
type DescribeUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDescribeUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDescribeUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/{user-id}] describeUser", response, response.Code())
	}
}

// NewDescribeUserOK creates a DescribeUserOK with default headers values
func NewDescribeUserOK() *DescribeUserOK {
	return &DescribeUserOK{}
}

/*
DescribeUserOK describes a response with status code 200, with default header values.

A successful response
*/
type DescribeUserOK struct {
	Payload *DescribeUserOKBody
}

// IsSuccess returns true when this describe user o k response has a 2xx status code
func (o *DescribeUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this describe user o k response has a 3xx status code
func (o *DescribeUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe user o k response has a 4xx status code
func (o *DescribeUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe user o k response has a 5xx status code
func (o *DescribeUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this describe user o k response a status code equal to that given
func (o *DescribeUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the describe user o k response
func (o *DescribeUserOK) Code() int {
	return 200
}

func (o *DescribeUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserOK %s", 200, payload)
}

func (o *DescribeUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserOK %s", 200, payload)
}

func (o *DescribeUserOK) GetPayload() *DescribeUserOKBody {
	return o.Payload
}

func (o *DescribeUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DescribeUserOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeUserBadRequest creates a DescribeUserBadRequest with default headers values
func NewDescribeUserBadRequest() *DescribeUserBadRequest {
	return &DescribeUserBadRequest{}
}

/*
DescribeUserBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DescribeUserBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe user bad request response has a 2xx status code
func (o *DescribeUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe user bad request response has a 3xx status code
func (o *DescribeUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe user bad request response has a 4xx status code
func (o *DescribeUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe user bad request response has a 5xx status code
func (o *DescribeUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this describe user bad request response a status code equal to that given
func (o *DescribeUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the describe user bad request response
func (o *DescribeUserBadRequest) Code() int {
	return 400
}

func (o *DescribeUserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserBadRequest %s", 400, payload)
}

func (o *DescribeUserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserBadRequest %s", 400, payload)
}

func (o *DescribeUserBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeUserUnauthorized creates a DescribeUserUnauthorized with default headers values
func NewDescribeUserUnauthorized() *DescribeUserUnauthorized {
	return &DescribeUserUnauthorized{}
}

/*
DescribeUserUnauthorized describes a response with status code 401, with default header values.

Incorrect username or password.
*/
type DescribeUserUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe user unauthorized response has a 2xx status code
func (o *DescribeUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe user unauthorized response has a 3xx status code
func (o *DescribeUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe user unauthorized response has a 4xx status code
func (o *DescribeUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe user unauthorized response has a 5xx status code
func (o *DescribeUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this describe user unauthorized response a status code equal to that given
func (o *DescribeUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the describe user unauthorized response
func (o *DescribeUserUnauthorized) Code() int {
	return 401
}

func (o *DescribeUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserUnauthorized %s", 401, payload)
}

func (o *DescribeUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserUnauthorized %s", 401, payload)
}

func (o *DescribeUserUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeUserInternalServerError creates a DescribeUserInternalServerError with default headers values
func NewDescribeUserInternalServerError() *DescribeUserInternalServerError {
	return &DescribeUserInternalServerError{}
}

/*
DescribeUserInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DescribeUserInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe user internal server error response has a 2xx status code
func (o *DescribeUserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe user internal server error response has a 3xx status code
func (o *DescribeUserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe user internal server error response has a 4xx status code
func (o *DescribeUserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe user internal server error response has a 5xx status code
func (o *DescribeUserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this describe user internal server error response a status code equal to that given
func (o *DescribeUserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the describe user internal server error response
func (o *DescribeUserInternalServerError) Code() int {
	return 500
}

func (o *DescribeUserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserInternalServerError %s", 500, payload)
}

func (o *DescribeUserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/{user-id}][%d] describeUserInternalServerError %s", 500, payload)
}

func (o *DescribeUserInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DescribeUserOKBody describe user o k body
swagger:model DescribeUserOKBody
*/
type DescribeUserOKBody struct {

	// Email address of the user
	Email string `json:"email,omitempty"`

	// The state of the user (enabled or disabled)
	// Required: true
	Enabled *bool `json:"enabled"`

	// First name of the user
	Firstname string `json:"firstname,omitempty"`

	// Last name of the user
	Lastname string `json:"lastname,omitempty"`

	// Tags associated with the User
	Tags []string `json:"tags"`

	// The unique ID of the user
	UserID string `json:"user-id,omitempty"`

	// The username of the user
	Username string `json:"username,omitempty"`
}

// Validate validates this describe user o k body
func (o *DescribeUserOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeUserOKBody) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("describeUserOK"+"."+"enabled", "body", o.Enabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this describe user o k body based on context it is used
func (o *DescribeUserOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DescribeUserOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DescribeUserOKBody) UnmarshalBinary(b []byte) error {
	var res DescribeUserOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
