// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeVMParams creates a new DescribeVMParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeVMParams() *DescribeVMParams {
	return NewDescribeVMParamsWithTimeout(cr.DefaultTimeout)
}

// NewDescribeVMParamsWithTimeout creates a new DescribeVMParams object
// with the ability to set a timeout on a request.
func NewDescribeVMParamsWithTimeout(timeout time.Duration) *DescribeVMParams {
	return &DescribeVMParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDescribeVMParamsWithContext creates a new DescribeVMParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVMParams].
func NewDescribeVMParamsWithContext(ctx context.Context) *DescribeVMParams {
	return &DescribeVMParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDescribeVMParamsWithHTTPClient creates a new DescribeVMParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeVMParamsWithHTTPClient(client *http.Client) *DescribeVMParams {
	return &DescribeVMParams{
		HTTPClient: client,
	}
}

/*
DescribeVMParams contains all the parameters to send to the API endpoint

	for the describe Vm operation.

	Typically these are written to a http.Request.
*/
type DescribeVMParams struct {

	/* InstanceID.

	   Specify the unique instance ID of the virtual machine. (Required)
	*/
	InstanceID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the describe Vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeVMParams) WithDefaults() *DescribeVMParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe Vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeVMParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe Vm params.
func (o *DescribeVMParams) WithTimeout(timeout time.Duration) *DescribeVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe Vm params.
func (o *DescribeVMParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the describe Vm params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVMParams].
func (o *DescribeVMParams) WithContext(ctx context.Context) *DescribeVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe Vm params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeVMParams].
func (o *DescribeVMParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the describe Vm params.
func (o *DescribeVMParams) WithHTTPClient(client *http.Client) *DescribeVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe Vm params.
func (o *DescribeVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the describe Vm params.
func (o *DescribeVMParams) WithInstanceID(instanceID string) *DescribeVMParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the describe Vm params.
func (o *DescribeVMParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DescribeVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance-id
	if err := r.SetPathParam("instance-id", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
