// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeNetworkParams creates a new DescribeNetworkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDescribeNetworkParams() *DescribeNetworkParams {
	return NewDescribeNetworkParamsWithTimeout(cr.DefaultTimeout)
}

// NewDescribeNetworkParamsWithTimeout creates a new DescribeNetworkParams object
// with the ability to set a timeout on a request.
func NewDescribeNetworkParamsWithTimeout(timeout time.Duration) *DescribeNetworkParams {
	return &DescribeNetworkParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDescribeNetworkParamsWithContext creates a new DescribeNetworkParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeNetworkParams].
func NewDescribeNetworkParamsWithContext(ctx context.Context) *DescribeNetworkParams {
	return &DescribeNetworkParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDescribeNetworkParamsWithHTTPClient creates a new DescribeNetworkParams object
// with the ability to set a custom HTTPClient for a request.
func NewDescribeNetworkParamsWithHTTPClient(client *http.Client) *DescribeNetworkParams {
	return &DescribeNetworkParams{
		HTTPClient: client,
	}
}

/*
DescribeNetworkParams contains all the parameters to send to the API endpoint

	for the describe network operation.

	Typically these are written to a http.Request.
*/
type DescribeNetworkParams struct {

	/* NetworkID.

	   The ID of the network to describe
	*/
	NetworkID string

	/* Property.

	   Display value of a specific property of the network.
	*/
	Property *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the describe network params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeNetworkParams) WithDefaults() *DescribeNetworkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the describe network params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DescribeNetworkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the describe network params.
func (o *DescribeNetworkParams) WithTimeout(timeout time.Duration) *DescribeNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe network params.
func (o *DescribeNetworkParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the describe network params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeNetworkParams].
func (o *DescribeNetworkParams) WithContext(ctx context.Context) *DescribeNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe network params.
//
// Deprecated: use the operation call with context to pass the context instead of [DescribeNetworkParams].
func (o *DescribeNetworkParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the describe network params.
func (o *DescribeNetworkParams) WithHTTPClient(client *http.Client) *DescribeNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe network params.
func (o *DescribeNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the describe network params.
func (o *DescribeNetworkParams) WithNetworkID(networkID string) *DescribeNetworkParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the describe network params.
func (o *DescribeNetworkParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithProperty adds the property to the describe network params.
func (o *DescribeNetworkParams) WithProperty(property *string) *DescribeNetworkParams {
	o.SetProperty(property)
	return o
}

// SetProperty adds the property to the describe network params.
func (o *DescribeNetworkParams) SetProperty(property *string) {
	o.Property = property
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DescribeNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param network-id
	if err := r.SetPathParam("network-id", o.NetworkID); err != nil {
		return err
	}

	if o.Property != nil {

		// query param property
		var qrProperty string

		if o.Property != nil {
			qrProperty = *o.Property
		}
		qProperty := qrProperty
		if qProperty != "" {

			if err := r.SetQueryParam("property", qProperty); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
