// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DescribeTenantReader is a Reader for the DescribeTenant structure.
type DescribeTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeTenantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeTenantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tenants/{tenant-id}] describeTenant", response, response.Code())
	}
}

// NewDescribeTenantOK creates a DescribeTenantOK with default headers values
func NewDescribeTenantOK() *DescribeTenantOK {
	return &DescribeTenantOK{}
}

/*
DescribeTenantOK describes a response with status code 200, with default header values.

A successful response
*/
type DescribeTenantOK struct {
	Payload *DescribeTenantOKBody
}

// IsSuccess returns true when this describe tenant o k response has a 2xx status code
func (o *DescribeTenantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this describe tenant o k response has a 3xx status code
func (o *DescribeTenantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe tenant o k response has a 4xx status code
func (o *DescribeTenantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this describe tenant o k response has a 5xx status code
func (o *DescribeTenantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this describe tenant o k response a status code equal to that given
func (o *DescribeTenantOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the describe tenant o k response
func (o *DescribeTenantOK) Code() int {
	return 200
}

func (o *DescribeTenantOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/{tenant-id}][%d] describeTenantOK %s", 200, payload)
}

func (o *DescribeTenantOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/{tenant-id}][%d] describeTenantOK %s", 200, payload)
}

func (o *DescribeTenantOK) GetPayload() *DescribeTenantOKBody {
	return o.Payload
}

func (o *DescribeTenantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DescribeTenantOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDescribeTenantBadRequest creates a DescribeTenantBadRequest with default headers values
func NewDescribeTenantBadRequest() *DescribeTenantBadRequest {
	return &DescribeTenantBadRequest{}
}

/*
DescribeTenantBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DescribeTenantBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this describe tenant bad request response has a 2xx status code
func (o *DescribeTenantBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this describe tenant bad request response has a 3xx status code
func (o *DescribeTenantBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this describe tenant bad request response has a 4xx status code
func (o *DescribeTenantBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this describe tenant bad request response has a 5xx status code
func (o *DescribeTenantBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this describe tenant bad request response a status code equal to that given
func (o *DescribeTenantBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the describe tenant bad request response
func (o *DescribeTenantBadRequest) Code() int {
	return 400
}

func (o *DescribeTenantBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/{tenant-id}][%d] describeTenantBadRequest %s", 400, payload)
}

func (o *DescribeTenantBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/{tenant-id}][%d] describeTenantBadRequest %s", 400, payload)
}

func (o *DescribeTenantBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeTenantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DescribeTenantOKBody describe tenant o k body
swagger:model DescribeTenantOKBody
*/
type DescribeTenantOKBody struct {

	// Description of the tenant
	Description string `json:"description,omitempty"`

	// Tenant contact email
	Email string `json:"email,omitempty"`

	// The state of the tenant (enabled or disabled)
	// Required: true
	Enabled *bool `json:"enabled"`

	// Unique ID of the tenant
	ID string `json:"id,omitempty"`

	// Name of the tenant
	Name string `json:"name,omitempty"`

	// Tags associated with the Tenant
	Tags []string `json:"tags"`
}

// Validate validates this describe tenant o k body
func (o *DescribeTenantOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DescribeTenantOKBody) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("describeTenantOK"+"."+"enabled", "body", o.Enabled); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this describe tenant o k body based on context it is used
func (o *DescribeTenantOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DescribeTenantOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DescribeTenantOKBody) UnmarshalBinary(b []byte) error {
	var res DescribeTenantOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
