// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDetachRoleFromUserParams creates a new DetachRoleFromUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDetachRoleFromUserParams() *DetachRoleFromUserParams {
	return NewDetachRoleFromUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewDetachRoleFromUserParamsWithTimeout creates a new DetachRoleFromUserParams object
// with the ability to set a timeout on a request.
func NewDetachRoleFromUserParamsWithTimeout(timeout time.Duration) *DetachRoleFromUserParams {
	return &DetachRoleFromUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewDetachRoleFromUserParamsWithContext creates a new DetachRoleFromUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [DetachRoleFromUserParams].
func NewDetachRoleFromUserParamsWithContext(ctx context.Context) *DetachRoleFromUserParams {
	return &DetachRoleFromUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewDetachRoleFromUserParamsWithHTTPClient creates a new DetachRoleFromUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewDetachRoleFromUserParamsWithHTTPClient(client *http.Client) *DetachRoleFromUserParams {
	return &DetachRoleFromUserParams{
		HTTPClient: client,
	}
}

/*
DetachRoleFromUserParams contains all the parameters to send to the API endpoint

	for the detach role from user operation.

	Typically these are written to a http.Request.
*/
type DetachRoleFromUserParams struct {

	/* Role.

	   Name of the role to detach. (Required)
	*/
	Role string

	/* UserID.

	   Username or email of the user. (Required)
	*/
	UserID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the detach role from user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DetachRoleFromUserParams) WithDefaults() *DetachRoleFromUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the detach role from user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DetachRoleFromUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the detach role from user params.
func (o *DetachRoleFromUserParams) WithTimeout(timeout time.Duration) *DetachRoleFromUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the detach role from user params.
func (o *DetachRoleFromUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the detach role from user params.
//
// Deprecated: use the operation call with context to pass the context instead of [DetachRoleFromUserParams].
func (o *DetachRoleFromUserParams) WithContext(ctx context.Context) *DetachRoleFromUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the detach role from user params.
//
// Deprecated: use the operation call with context to pass the context instead of [DetachRoleFromUserParams].
func (o *DetachRoleFromUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the detach role from user params.
func (o *DetachRoleFromUserParams) WithHTTPClient(client *http.Client) *DetachRoleFromUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the detach role from user params.
func (o *DetachRoleFromUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the detach role from user params.
func (o *DetachRoleFromUserParams) WithRole(role string) *DetachRoleFromUserParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the detach role from user params.
func (o *DetachRoleFromUserParams) SetRole(role string) {
	o.Role = role
}

// WithUserID adds the userID to the detach role from user params.
func (o *DetachRoleFromUserParams) WithUserID(userID string) *DetachRoleFromUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the detach role from user params.
func (o *DetachRoleFromUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *DetachRoleFromUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	// path param user-id
	if err := r.SetPathParam("user-id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
