// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// DetachVolumeFromVMReader is a Reader for the DetachVolumeFromVM structure.
type DetachVolumeFromVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetachVolumeFromVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewDetachVolumeFromVMAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDetachVolumeFromVMBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /compute/volumes/{volume-id}/detach/{instance-id}] detachVolumeFromVm", response, response.Code())
	}
}

// NewDetachVolumeFromVMAccepted creates a DetachVolumeFromVMAccepted with default headers values
func NewDetachVolumeFromVMAccepted() *DetachVolumeFromVMAccepted {
	return &DetachVolumeFromVMAccepted{}
}

/*
DetachVolumeFromVMAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for detaching volume from VM
*/
type DetachVolumeFromVMAccepted struct {
	Payload *DetachVolumeFromVMAcceptedBody
}

// IsSuccess returns true when this detach volume from Vm accepted response has a 2xx status code
func (o *DetachVolumeFromVMAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this detach volume from Vm accepted response has a 3xx status code
func (o *DetachVolumeFromVMAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this detach volume from Vm accepted response has a 4xx status code
func (o *DetachVolumeFromVMAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this detach volume from Vm accepted response has a 5xx status code
func (o *DetachVolumeFromVMAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this detach volume from Vm accepted response a status code equal to that given
func (o *DetachVolumeFromVMAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the detach volume from Vm accepted response
func (o *DetachVolumeFromVMAccepted) Code() int {
	return 202
}

func (o *DetachVolumeFromVMAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compute/volumes/{volume-id}/detach/{instance-id}][%d] detachVolumeFromVmAccepted %s", 202, payload)
}

func (o *DetachVolumeFromVMAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compute/volumes/{volume-id}/detach/{instance-id}][%d] detachVolumeFromVmAccepted %s", 202, payload)
}

func (o *DetachVolumeFromVMAccepted) GetPayload() *DetachVolumeFromVMAcceptedBody {
	return o.Payload
}

func (o *DetachVolumeFromVMAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DetachVolumeFromVMAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDetachVolumeFromVMBadRequest creates a DetachVolumeFromVMBadRequest with default headers values
func NewDetachVolumeFromVMBadRequest() *DetachVolumeFromVMBadRequest {
	return &DetachVolumeFromVMBadRequest{}
}

/*
DetachVolumeFromVMBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type DetachVolumeFromVMBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this detach volume from Vm bad request response has a 2xx status code
func (o *DetachVolumeFromVMBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this detach volume from Vm bad request response has a 3xx status code
func (o *DetachVolumeFromVMBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this detach volume from Vm bad request response has a 4xx status code
func (o *DetachVolumeFromVMBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this detach volume from Vm bad request response has a 5xx status code
func (o *DetachVolumeFromVMBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this detach volume from Vm bad request response a status code equal to that given
func (o *DetachVolumeFromVMBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the detach volume from Vm bad request response
func (o *DetachVolumeFromVMBadRequest) Code() int {
	return 400
}

func (o *DetachVolumeFromVMBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compute/volumes/{volume-id}/detach/{instance-id}][%d] detachVolumeFromVmBadRequest %s", 400, payload)
}

func (o *DetachVolumeFromVMBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /compute/volumes/{volume-id}/detach/{instance-id}][%d] detachVolumeFromVmBadRequest %s", 400, payload)
}

func (o *DetachVolumeFromVMBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DetachVolumeFromVMBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DetachVolumeFromVMAcceptedBody detach volume from VM accepted body
swagger:model DetachVolumeFromVMAcceptedBody
*/
type DetachVolumeFromVMAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this detach volume from VM accepted body
func (o *DetachVolumeFromVMAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DetachVolumeFromVMAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("detachVolumeFromVmAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var detachVolumeFromVmAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		detachVolumeFromVmAcceptedBodyTypeStatusPropEnum = append(detachVolumeFromVmAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// DetachVolumeFromVMAcceptedBodyStatusAccepted captures enum value "accepted"
	DetachVolumeFromVMAcceptedBodyStatusAccepted string = "accepted"

	// DetachVolumeFromVMAcceptedBodyStatusCompleted captures enum value "completed"
	DetachVolumeFromVMAcceptedBodyStatusCompleted string = "completed"

	// DetachVolumeFromVMAcceptedBodyStatusFailed captures enum value "failed"
	DetachVolumeFromVMAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *DetachVolumeFromVMAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, detachVolumeFromVmAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *DetachVolumeFromVMAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("detachVolumeFromVmAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *DetachVolumeFromVMAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("detachVolumeFromVmAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this detach volume from VM accepted body based on context it is used
func (o *DetachVolumeFromVMAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DetachVolumeFromVMAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DetachVolumeFromVMAcceptedBody) UnmarshalBinary(b []byte) error {
	var res DetachVolumeFromVMAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
