// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ExportRolesReader is a Reader for the ExportRoles structure.
type ExportRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewExportRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExportRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExportRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExportRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /roles/export] exportRoles", response, response.Code())
	}
}

// NewExportRolesOK creates a ExportRolesOK with default headers values
func NewExportRolesOK() *ExportRolesOK {
	return &ExportRolesOK{}
}

/*
ExportRolesOK describes a response with status code 200, with default header values.

A successful response with the exported role data.
*/
type ExportRolesOK struct {
	Payload *ExportRolesOKBody
}

// IsSuccess returns true when this export roles o k response has a 2xx status code
func (o *ExportRolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this export roles o k response has a 3xx status code
func (o *ExportRolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export roles o k response has a 4xx status code
func (o *ExportRolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this export roles o k response has a 5xx status code
func (o *ExportRolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this export roles o k response a status code equal to that given
func (o *ExportRolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the export roles o k response
func (o *ExportRolesOK) Code() int {
	return 200
}

func (o *ExportRolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesOK %s", 200, payload)
}

func (o *ExportRolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesOK %s", 200, payload)
}

func (o *ExportRolesOK) GetPayload() *ExportRolesOKBody {
	return o.Payload
}

func (o *ExportRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ExportRolesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExportRolesBadRequest creates a ExportRolesBadRequest with default headers values
func NewExportRolesBadRequest() *ExportRolesBadRequest {
	return &ExportRolesBadRequest{}
}

/*
ExportRolesBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ExportRolesBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this export roles bad request response has a 2xx status code
func (o *ExportRolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this export roles bad request response has a 3xx status code
func (o *ExportRolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export roles bad request response has a 4xx status code
func (o *ExportRolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this export roles bad request response has a 5xx status code
func (o *ExportRolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this export roles bad request response a status code equal to that given
func (o *ExportRolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the export roles bad request response
func (o *ExportRolesBadRequest) Code() int {
	return 400
}

func (o *ExportRolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesBadRequest %s", 400, payload)
}

func (o *ExportRolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesBadRequest %s", 400, payload)
}

func (o *ExportRolesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ExportRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExportRolesUnauthorized creates a ExportRolesUnauthorized with default headers values
func NewExportRolesUnauthorized() *ExportRolesUnauthorized {
	return &ExportRolesUnauthorized{}
}

/*
ExportRolesUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type ExportRolesUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this export roles unauthorized response has a 2xx status code
func (o *ExportRolesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this export roles unauthorized response has a 3xx status code
func (o *ExportRolesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export roles unauthorized response has a 4xx status code
func (o *ExportRolesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this export roles unauthorized response has a 5xx status code
func (o *ExportRolesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this export roles unauthorized response a status code equal to that given
func (o *ExportRolesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the export roles unauthorized response
func (o *ExportRolesUnauthorized) Code() int {
	return 401
}

func (o *ExportRolesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesUnauthorized %s", 401, payload)
}

func (o *ExportRolesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesUnauthorized %s", 401, payload)
}

func (o *ExportRolesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ExportRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExportRolesInternalServerError creates a ExportRolesInternalServerError with default headers values
func NewExportRolesInternalServerError() *ExportRolesInternalServerError {
	return &ExportRolesInternalServerError{}
}

/*
ExportRolesInternalServerError describes a response with status code 500, with default header values.

Internal server error during export.
*/
type ExportRolesInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this export roles internal server error response has a 2xx status code
func (o *ExportRolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this export roles internal server error response has a 3xx status code
func (o *ExportRolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this export roles internal server error response has a 4xx status code
func (o *ExportRolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this export roles internal server error response has a 5xx status code
func (o *ExportRolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this export roles internal server error response a status code equal to that given
func (o *ExportRolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the export roles internal server error response
func (o *ExportRolesInternalServerError) Code() int {
	return 500
}

func (o *ExportRolesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesInternalServerError %s", 500, payload)
}

func (o *ExportRolesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/export][%d] exportRolesInternalServerError %s", 500, payload)
}

func (o *ExportRolesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ExportRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ExportRolesOKBody export roles o k body
swagger:model ExportRolesOKBody
*/
type ExportRolesOKBody struct {

	// Number of roles exported
	ExportedRolesCount int64 `json:"exported_roles_count,omitempty"`

	// Path where the export file was written
	OutputFile string `json:"output_file,omitempty"`
}

// Validate validates this export roles o k body
func (o *ExportRolesOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this export roles o k body based on context it is used
func (o *ExportRolesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ExportRolesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportRolesOKBody) UnmarshalBinary(b []byte) error {
	var res ExportRolesOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
