// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// GetRoleEffectivePermissionsReader is a Reader for the GetRoleEffectivePermissions structure.
type GetRoleEffectivePermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoleEffectivePermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoleEffectivePermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRoleEffectivePermissionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetRoleEffectivePermissionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRoleEffectivePermissionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRoleEffectivePermissionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /roles/{name}/effective-permissions] getRoleEffectivePermissions", response, response.Code())
	}
}

// NewGetRoleEffectivePermissionsOK creates a GetRoleEffectivePermissionsOK with default headers values
func NewGetRoleEffectivePermissionsOK() *GetRoleEffectivePermissionsOK {
	return &GetRoleEffectivePermissionsOK{}
}

/*
GetRoleEffectivePermissionsOK describes a response with status code 200, with default header values.

A successful response with the flattened (effective) permissions.
*/
type GetRoleEffectivePermissionsOK struct {
	Payload []*GetRoleEffectivePermissionsOKBodyItems0
}

// IsSuccess returns true when this get role effective permissions o k response has a 2xx status code
func (o *GetRoleEffectivePermissionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get role effective permissions o k response has a 3xx status code
func (o *GetRoleEffectivePermissionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get role effective permissions o k response has a 4xx status code
func (o *GetRoleEffectivePermissionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get role effective permissions o k response has a 5xx status code
func (o *GetRoleEffectivePermissionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get role effective permissions o k response a status code equal to that given
func (o *GetRoleEffectivePermissionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get role effective permissions o k response
func (o *GetRoleEffectivePermissionsOK) Code() int {
	return 200
}

func (o *GetRoleEffectivePermissionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsOK %s", 200, payload)
}

func (o *GetRoleEffectivePermissionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsOK %s", 200, payload)
}

func (o *GetRoleEffectivePermissionsOK) GetPayload() []*GetRoleEffectivePermissionsOKBodyItems0 {
	return o.Payload
}

func (o *GetRoleEffectivePermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRoleEffectivePermissionsBadRequest creates a GetRoleEffectivePermissionsBadRequest with default headers values
func NewGetRoleEffectivePermissionsBadRequest() *GetRoleEffectivePermissionsBadRequest {
	return &GetRoleEffectivePermissionsBadRequest{}
}

/*
GetRoleEffectivePermissionsBadRequest describes a response with status code 400, with default header values.

Invalid role name provided.
*/
type GetRoleEffectivePermissionsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get role effective permissions bad request response has a 2xx status code
func (o *GetRoleEffectivePermissionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get role effective permissions bad request response has a 3xx status code
func (o *GetRoleEffectivePermissionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get role effective permissions bad request response has a 4xx status code
func (o *GetRoleEffectivePermissionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get role effective permissions bad request response has a 5xx status code
func (o *GetRoleEffectivePermissionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get role effective permissions bad request response a status code equal to that given
func (o *GetRoleEffectivePermissionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get role effective permissions bad request response
func (o *GetRoleEffectivePermissionsBadRequest) Code() int {
	return 400
}

func (o *GetRoleEffectivePermissionsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsBadRequest %s", 400, payload)
}

func (o *GetRoleEffectivePermissionsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsBadRequest %s", 400, payload)
}

func (o *GetRoleEffectivePermissionsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRoleEffectivePermissionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRoleEffectivePermissionsUnauthorized creates a GetRoleEffectivePermissionsUnauthorized with default headers values
func NewGetRoleEffectivePermissionsUnauthorized() *GetRoleEffectivePermissionsUnauthorized {
	return &GetRoleEffectivePermissionsUnauthorized{}
}

/*
GetRoleEffectivePermissionsUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type GetRoleEffectivePermissionsUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get role effective permissions unauthorized response has a 2xx status code
func (o *GetRoleEffectivePermissionsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get role effective permissions unauthorized response has a 3xx status code
func (o *GetRoleEffectivePermissionsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get role effective permissions unauthorized response has a 4xx status code
func (o *GetRoleEffectivePermissionsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get role effective permissions unauthorized response has a 5xx status code
func (o *GetRoleEffectivePermissionsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get role effective permissions unauthorized response a status code equal to that given
func (o *GetRoleEffectivePermissionsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get role effective permissions unauthorized response
func (o *GetRoleEffectivePermissionsUnauthorized) Code() int {
	return 401
}

func (o *GetRoleEffectivePermissionsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsUnauthorized %s", 401, payload)
}

func (o *GetRoleEffectivePermissionsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsUnauthorized %s", 401, payload)
}

func (o *GetRoleEffectivePermissionsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRoleEffectivePermissionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRoleEffectivePermissionsNotFound creates a GetRoleEffectivePermissionsNotFound with default headers values
func NewGetRoleEffectivePermissionsNotFound() *GetRoleEffectivePermissionsNotFound {
	return &GetRoleEffectivePermissionsNotFound{}
}

/*
GetRoleEffectivePermissionsNotFound describes a response with status code 404, with default header values.

Role not found.
*/
type GetRoleEffectivePermissionsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get role effective permissions not found response has a 2xx status code
func (o *GetRoleEffectivePermissionsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get role effective permissions not found response has a 3xx status code
func (o *GetRoleEffectivePermissionsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get role effective permissions not found response has a 4xx status code
func (o *GetRoleEffectivePermissionsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get role effective permissions not found response has a 5xx status code
func (o *GetRoleEffectivePermissionsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get role effective permissions not found response a status code equal to that given
func (o *GetRoleEffectivePermissionsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get role effective permissions not found response
func (o *GetRoleEffectivePermissionsNotFound) Code() int {
	return 404
}

func (o *GetRoleEffectivePermissionsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsNotFound %s", 404, payload)
}

func (o *GetRoleEffectivePermissionsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsNotFound %s", 404, payload)
}

func (o *GetRoleEffectivePermissionsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRoleEffectivePermissionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetRoleEffectivePermissionsInternalServerError creates a GetRoleEffectivePermissionsInternalServerError with default headers values
func NewGetRoleEffectivePermissionsInternalServerError() *GetRoleEffectivePermissionsInternalServerError {
	return &GetRoleEffectivePermissionsInternalServerError{}
}

/*
GetRoleEffectivePermissionsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetRoleEffectivePermissionsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get role effective permissions internal server error response has a 2xx status code
func (o *GetRoleEffectivePermissionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get role effective permissions internal server error response has a 3xx status code
func (o *GetRoleEffectivePermissionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get role effective permissions internal server error response has a 4xx status code
func (o *GetRoleEffectivePermissionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get role effective permissions internal server error response has a 5xx status code
func (o *GetRoleEffectivePermissionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get role effective permissions internal server error response a status code equal to that given
func (o *GetRoleEffectivePermissionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get role effective permissions internal server error response
func (o *GetRoleEffectivePermissionsInternalServerError) Code() int {
	return 500
}

func (o *GetRoleEffectivePermissionsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsInternalServerError %s", 500, payload)
}

func (o *GetRoleEffectivePermissionsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/{name}/effective-permissions][%d] getRoleEffectivePermissionsInternalServerError %s", 500, payload)
}

func (o *GetRoleEffectivePermissionsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRoleEffectivePermissionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetRoleEffectivePermissionsOKBodyItems0 get role effective permissions o k body items0
swagger:model GetRoleEffectivePermissionsOKBodyItems0
*/
type GetRoleEffectivePermissionsOKBodyItems0 struct {

	// The permission name in format <module>:<resource>:<action>
	// Example: compute:vm:create
	Name string `json:"name,omitempty"`

	// Which roles contribute this permission (direct or inherited)
	SourcePermissions []string `json:"source_permissions"`

	// Total number of effective permissions after flattening
	Total int64 `json:"total,omitempty"`
}

// Validate validates this get role effective permissions o k body items0
func (o *GetRoleEffectivePermissionsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get role effective permissions o k body items0 based on context it is used
func (o *GetRoleEffectivePermissionsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetRoleEffectivePermissionsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetRoleEffectivePermissionsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetRoleEffectivePermissionsOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
