// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// GetHelloReader is a Reader for the GetHello structure.
type GetHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetHelloOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetHelloBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /hello] getHello", response, response.Code())
	}
}

// NewGetHelloOK creates a GetHelloOK with default headers values
func NewGetHelloOK() *GetHelloOK {
	return &GetHelloOK{}
}

/*
GetHelloOK describes a response with status code 200, with default header values.

A successful response
*/
type GetHelloOK struct {
	Payload *GetHelloOKBody
}

// IsSuccess returns true when this get hello o k response has a 2xx status code
func (o *GetHelloOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get hello o k response has a 3xx status code
func (o *GetHelloOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get hello o k response has a 4xx status code
func (o *GetHelloOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get hello o k response has a 5xx status code
func (o *GetHelloOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get hello o k response a status code equal to that given
func (o *GetHelloOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get hello o k response
func (o *GetHelloOK) Code() int {
	return 200
}

func (o *GetHelloOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hello][%d] getHelloOK %s", 200, payload)
}

func (o *GetHelloOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hello][%d] getHelloOK %s", 200, payload)
}

func (o *GetHelloOK) GetPayload() *GetHelloOKBody {
	return o.Payload
}

func (o *GetHelloOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetHelloOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetHelloBadRequest creates a GetHelloBadRequest with default headers values
func NewGetHelloBadRequest() *GetHelloBadRequest {
	return &GetHelloBadRequest{}
}

/*
GetHelloBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type GetHelloBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get hello bad request response has a 2xx status code
func (o *GetHelloBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get hello bad request response has a 3xx status code
func (o *GetHelloBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get hello bad request response has a 4xx status code
func (o *GetHelloBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get hello bad request response has a 5xx status code
func (o *GetHelloBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get hello bad request response a status code equal to that given
func (o *GetHelloBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get hello bad request response
func (o *GetHelloBadRequest) Code() int {
	return 400
}

func (o *GetHelloBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hello][%d] getHelloBadRequest %s", 400, payload)
}

func (o *GetHelloBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /hello][%d] getHelloBadRequest %s", 400, payload)
}

func (o *GetHelloBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHelloBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetHelloOKBody Greeting
swagger:model GetHelloOKBody
*/
type GetHelloOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get hello o k body
func (o *GetHelloOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get hello o k body based on context it is used
func (o *GetHelloOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetHelloOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetHelloOKBody) UnmarshalBinary(b []byte) error {
	var res GetHelloOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
