// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// GetTokenReader is a Reader for the GetToken structure.
type GetTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /token] getToken", response, response.Code())
	}
}

// NewGetTokenOK creates a GetTokenOK with default headers values
func NewGetTokenOK() *GetTokenOK {
	return &GetTokenOK{}
}

/*
GetTokenOK describes a response with status code 200, with default header values.

Successful token retrieval.
*/
type GetTokenOK struct {
	Payload *GetTokenOKBody
}

// IsSuccess returns true when this get token o k response has a 2xx status code
func (o *GetTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get token o k response has a 3xx status code
func (o *GetTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token o k response has a 4xx status code
func (o *GetTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get token o k response has a 5xx status code
func (o *GetTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get token o k response a status code equal to that given
func (o *GetTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get token o k response
func (o *GetTokenOK) Code() int {
	return 200
}

func (o *GetTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenOK %s", 200, payload)
}

func (o *GetTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenOK %s", 200, payload)
}

func (o *GetTokenOK) GetPayload() *GetTokenOKBody {
	return o.Payload
}

func (o *GetTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTokenOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTokenBadRequest creates a GetTokenBadRequest with default headers values
func NewGetTokenBadRequest() *GetTokenBadRequest {
	return &GetTokenBadRequest{}
}

/*
GetTokenBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type GetTokenBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get token bad request response has a 2xx status code
func (o *GetTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get token bad request response has a 3xx status code
func (o *GetTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token bad request response has a 4xx status code
func (o *GetTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get token bad request response has a 5xx status code
func (o *GetTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get token bad request response a status code equal to that given
func (o *GetTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get token bad request response
func (o *GetTokenBadRequest) Code() int {
	return 400
}

func (o *GetTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenBadRequest %s", 400, payload)
}

func (o *GetTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenBadRequest %s", 400, payload)
}

func (o *GetTokenBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTokenUnauthorized creates a GetTokenUnauthorized with default headers values
func NewGetTokenUnauthorized() *GetTokenUnauthorized {
	return &GetTokenUnauthorized{}
}

/*
GetTokenUnauthorized describes a response with status code 401, with default header values.

Incorrect username or password.
*/
type GetTokenUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get token unauthorized response has a 2xx status code
func (o *GetTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get token unauthorized response has a 3xx status code
func (o *GetTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token unauthorized response has a 4xx status code
func (o *GetTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get token unauthorized response has a 5xx status code
func (o *GetTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get token unauthorized response a status code equal to that given
func (o *GetTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get token unauthorized response
func (o *GetTokenUnauthorized) Code() int {
	return 401
}

func (o *GetTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenUnauthorized %s", 401, payload)
}

func (o *GetTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenUnauthorized %s", 401, payload)
}

func (o *GetTokenUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTokenInternalServerError creates a GetTokenInternalServerError with default headers values
func NewGetTokenInternalServerError() *GetTokenInternalServerError {
	return &GetTokenInternalServerError{}
}

/*
GetTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetTokenInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get token internal server error response has a 2xx status code
func (o *GetTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get token internal server error response has a 3xx status code
func (o *GetTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get token internal server error response has a 4xx status code
func (o *GetTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get token internal server error response has a 5xx status code
func (o *GetTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get token internal server error response a status code equal to that given
func (o *GetTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get token internal server error response
func (o *GetTokenInternalServerError) Code() int {
	return 500
}

func (o *GetTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenInternalServerError %s", 500, payload)
}

func (o *GetTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /token][%d] getTokenInternalServerError %s", 500, payload)
}

func (o *GetTokenInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetTokenOKBody get token o k body
swagger:model GetTokenOKBody
*/
type GetTokenOKBody struct {

	// An OAuth2 access token used for authorized communication with the server
	AccessToken string `json:"access_token,omitempty"`

	// Duration in seconds after which the access token will expire
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// Expiry time in ISO 8601 format (e.g., 0001-01-01T00:00:00Z)
	Expiry string `json:"expiry,omitempty"`

	// A token used to obtain a new access token once the current one expires
	RefreshToken string `json:"refresh_token,omitempty"`

	// Type of the token (e.g., Bearer)
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this get token o k body
func (o *GetTokenOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get token o k body based on context it is used
func (o *GetTokenOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTokenOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTokenOKBody) UnmarshalBinary(b []byte) error {
	var res GetTokenOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
