// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKvstoregetParams creates a new KvstoregetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewKvstoregetParams() *KvstoregetParams {
	return NewKvstoregetParamsWithTimeout(cr.DefaultTimeout)
}

// NewKvstoregetParamsWithTimeout creates a new KvstoregetParams object
// with the ability to set a timeout on a request.
func NewKvstoregetParamsWithTimeout(timeout time.Duration) *KvstoregetParams {
	return &KvstoregetParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewKvstoregetParamsWithContext creates a new KvstoregetParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [KvstoregetParams].
func NewKvstoregetParamsWithContext(ctx context.Context) *KvstoregetParams {
	return &KvstoregetParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewKvstoregetParamsWithHTTPClient creates a new KvstoregetParams object
// with the ability to set a custom HTTPClient for a request.
func NewKvstoregetParamsWithHTTPClient(client *http.Client) *KvstoregetParams {
	return &KvstoregetParams{
		HTTPClient: client,
	}
}

/*
KvstoregetParams contains all the parameters to send to the API endpoint

	for the kvstoreget operation.

	Typically these are written to a http.Request.
*/
type KvstoregetParams struct {

	/* Bucket.

	   Parameter bucket (string)
	*/
	Bucket string

	/* Key.

	   Parameter key (string)
	*/
	Key string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the kvstoreget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KvstoregetParams) WithDefaults() *KvstoregetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the kvstoreget params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *KvstoregetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the kvstoreget params.
func (o *KvstoregetParams) WithTimeout(timeout time.Duration) *KvstoregetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the kvstoreget params.
func (o *KvstoregetParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the kvstoreget params.
//
// Deprecated: use the operation call with context to pass the context instead of [KvstoregetParams].
func (o *KvstoregetParams) WithContext(ctx context.Context) *KvstoregetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the kvstoreget params.
//
// Deprecated: use the operation call with context to pass the context instead of [KvstoregetParams].
func (o *KvstoregetParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the kvstoreget params.
func (o *KvstoregetParams) WithHTTPClient(client *http.Client) *KvstoregetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the kvstoreget params.
func (o *KvstoregetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucket adds the bucket to the kvstoreget params.
func (o *KvstoregetParams) WithBucket(bucket string) *KvstoregetParams {
	o.SetBucket(bucket)
	return o
}

// SetBucket adds the bucket to the kvstoreget params.
func (o *KvstoregetParams) SetBucket(bucket string) {
	o.Bucket = bucket
}

// WithKey adds the key to the kvstoreget params.
func (o *KvstoregetParams) WithKey(key string) *KvstoregetParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the kvstoreget params.
func (o *KvstoregetParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *KvstoregetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucket
	if err := r.SetPathParam("bucket", o.Bucket); err != nil {
		return err
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
