// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// KvstoresetReader is a Reader for the Kvstoreset structure.
type KvstoresetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KvstoresetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKvstoresetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKvstoresetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /kvstore/{bucket}/{key}] kvstoreset", response, response.Code())
	}
}

// NewKvstoresetOK creates a KvstoresetOK with default headers values
func NewKvstoresetOK() *KvstoresetOK {
	return &KvstoresetOK{}
}

/*
KvstoresetOK describes a response with status code 200, with default header values.

Successful response
*/
type KvstoresetOK struct {
	Payload *KvstoresetOKBody
}

// IsSuccess returns true when this kvstoreset o k response has a 2xx status code
func (o *KvstoresetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kvstoreset o k response has a 3xx status code
func (o *KvstoresetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoreset o k response has a 4xx status code
func (o *KvstoresetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kvstoreset o k response has a 5xx status code
func (o *KvstoresetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoreset o k response a status code equal to that given
func (o *KvstoresetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kvstoreset o k response
func (o *KvstoresetOK) Code() int {
	return 200
}

func (o *KvstoresetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kvstore/{bucket}/{key}][%d] kvstoresetOK %s", 200, payload)
}

func (o *KvstoresetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kvstore/{bucket}/{key}][%d] kvstoresetOK %s", 200, payload)
}

func (o *KvstoresetOK) GetPayload() *KvstoresetOKBody {
	return o.Payload
}

func (o *KvstoresetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(KvstoresetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKvstoresetBadRequest creates a KvstoresetBadRequest with default headers values
func NewKvstoresetBadRequest() *KvstoresetBadRequest {
	return &KvstoresetBadRequest{}
}

/*
KvstoresetBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type KvstoresetBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this kvstoreset bad request response has a 2xx status code
func (o *KvstoresetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this kvstoreset bad request response has a 3xx status code
func (o *KvstoresetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoreset bad request response has a 4xx status code
func (o *KvstoresetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this kvstoreset bad request response has a 5xx status code
func (o *KvstoresetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoreset bad request response a status code equal to that given
func (o *KvstoresetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the kvstoreset bad request response
func (o *KvstoresetBadRequest) Code() int {
	return 400
}

func (o *KvstoresetBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kvstore/{bucket}/{key}][%d] kvstoresetBadRequest %s", 400, payload)
}

func (o *KvstoresetBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kvstore/{bucket}/{key}][%d] kvstoresetBadRequest %s", 400, payload)
}

func (o *KvstoresetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *KvstoresetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
KvstoresetOKBody kvstoreset o k body
swagger:model KvstoresetOKBody
*/
type KvstoresetOKBody struct {

	// Result
	Result string `json:"result,omitempty"`
}

// Validate validates this kvstoreset o k body
func (o *KvstoresetOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kvstoreset o k body based on context it is used
func (o *KvstoresetOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KvstoresetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KvstoresetOKBody) UnmarshalBinary(b []byte) error {
	var res KvstoresetOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
