// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// KvstoreexistsReader is a Reader for the Kvstoreexists structure.
type KvstoreexistsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KvstoreexistsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKvstoreexistsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKvstoreexistsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /kvstore/{bucket}/{key}/exists] kvstoreexists", response, response.Code())
	}
}

// NewKvstoreexistsOK creates a KvstoreexistsOK with default headers values
func NewKvstoreexistsOK() *KvstoreexistsOK {
	return &KvstoreexistsOK{}
}

/*
KvstoreexistsOK describes a response with status code 200, with default header values.

Successful response
*/
type KvstoreexistsOK struct {
	Payload *KvstoreexistsOKBody
}

// IsSuccess returns true when this kvstoreexists o k response has a 2xx status code
func (o *KvstoreexistsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kvstoreexists o k response has a 3xx status code
func (o *KvstoreexistsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoreexists o k response has a 4xx status code
func (o *KvstoreexistsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kvstoreexists o k response has a 5xx status code
func (o *KvstoreexistsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoreexists o k response a status code equal to that given
func (o *KvstoreexistsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kvstoreexists o k response
func (o *KvstoreexistsOK) Code() int {
	return 200
}

func (o *KvstoreexistsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kvstore/{bucket}/{key}/exists][%d] kvstoreexistsOK %s", 200, payload)
}

func (o *KvstoreexistsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kvstore/{bucket}/{key}/exists][%d] kvstoreexistsOK %s", 200, payload)
}

func (o *KvstoreexistsOK) GetPayload() *KvstoreexistsOKBody {
	return o.Payload
}

func (o *KvstoreexistsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(KvstoreexistsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKvstoreexistsBadRequest creates a KvstoreexistsBadRequest with default headers values
func NewKvstoreexistsBadRequest() *KvstoreexistsBadRequest {
	return &KvstoreexistsBadRequest{}
}

/*
KvstoreexistsBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type KvstoreexistsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this kvstoreexists bad request response has a 2xx status code
func (o *KvstoreexistsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this kvstoreexists bad request response has a 3xx status code
func (o *KvstoreexistsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoreexists bad request response has a 4xx status code
func (o *KvstoreexistsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this kvstoreexists bad request response has a 5xx status code
func (o *KvstoreexistsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoreexists bad request response a status code equal to that given
func (o *KvstoreexistsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the kvstoreexists bad request response
func (o *KvstoreexistsBadRequest) Code() int {
	return 400
}

func (o *KvstoreexistsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kvstore/{bucket}/{key}/exists][%d] kvstoreexistsBadRequest %s", 400, payload)
}

func (o *KvstoreexistsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /kvstore/{bucket}/{key}/exists][%d] kvstoreexistsBadRequest %s", 400, payload)
}

func (o *KvstoreexistsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *KvstoreexistsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
KvstoreexistsOKBody Response data
swagger:model KvstoreexistsOKBody
*/
type KvstoreexistsOKBody struct {

	// Result
	Result bool `json:"result,omitempty"`
}

// Validate validates this kvstoreexists o k body
func (o *KvstoreexistsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kvstoreexists o k body based on context it is used
func (o *KvstoreexistsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KvstoreexistsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KvstoreexistsOKBody) UnmarshalBinary(b []byte) error {
	var res KvstoreexistsOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
