// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// KvstoredeleteBucketReader is a Reader for the KvstoredeleteBucket structure.
type KvstoredeleteBucketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KvstoredeleteBucketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewKvstoredeleteBucketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKvstoredeleteBucketBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /kvstore/{bucket}] kvstoredeleteBucket", response, response.Code())
	}
}

// NewKvstoredeleteBucketOK creates a KvstoredeleteBucketOK with default headers values
func NewKvstoredeleteBucketOK() *KvstoredeleteBucketOK {
	return &KvstoredeleteBucketOK{}
}

/*
KvstoredeleteBucketOK describes a response with status code 200, with default header values.

Successful response
*/
type KvstoredeleteBucketOK struct {
	Payload *KvstoredeleteBucketOKBody
}

// IsSuccess returns true when this kvstoredelete bucket o k response has a 2xx status code
func (o *KvstoredeleteBucketOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this kvstoredelete bucket o k response has a 3xx status code
func (o *KvstoredeleteBucketOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoredelete bucket o k response has a 4xx status code
func (o *KvstoredeleteBucketOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this kvstoredelete bucket o k response has a 5xx status code
func (o *KvstoredeleteBucketOK) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoredelete bucket o k response a status code equal to that given
func (o *KvstoredeleteBucketOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the kvstoredelete bucket o k response
func (o *KvstoredeleteBucketOK) Code() int {
	return 200
}

func (o *KvstoredeleteBucketOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kvstore/{bucket}][%d] kvstoredeleteBucketOK %s", 200, payload)
}

func (o *KvstoredeleteBucketOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kvstore/{bucket}][%d] kvstoredeleteBucketOK %s", 200, payload)
}

func (o *KvstoredeleteBucketOK) GetPayload() *KvstoredeleteBucketOKBody {
	return o.Payload
}

func (o *KvstoredeleteBucketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(KvstoredeleteBucketOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewKvstoredeleteBucketBadRequest creates a KvstoredeleteBucketBadRequest with default headers values
func NewKvstoredeleteBucketBadRequest() *KvstoredeleteBucketBadRequest {
	return &KvstoredeleteBucketBadRequest{}
}

/*
KvstoredeleteBucketBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type KvstoredeleteBucketBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this kvstoredelete bucket bad request response has a 2xx status code
func (o *KvstoredeleteBucketBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this kvstoredelete bucket bad request response has a 3xx status code
func (o *KvstoredeleteBucketBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this kvstoredelete bucket bad request response has a 4xx status code
func (o *KvstoredeleteBucketBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this kvstoredelete bucket bad request response has a 5xx status code
func (o *KvstoredeleteBucketBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this kvstoredelete bucket bad request response a status code equal to that given
func (o *KvstoredeleteBucketBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the kvstoredelete bucket bad request response
func (o *KvstoredeleteBucketBadRequest) Code() int {
	return 400
}

func (o *KvstoredeleteBucketBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kvstore/{bucket}][%d] kvstoredeleteBucketBadRequest %s", 400, payload)
}

func (o *KvstoredeleteBucketBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /kvstore/{bucket}][%d] kvstoredeleteBucketBadRequest %s", 400, payload)
}

func (o *KvstoredeleteBucketBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *KvstoredeleteBucketBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
KvstoredeleteBucketOKBody kvstoredelete bucket o k body
swagger:model KvstoredeleteBucketOKBody
*/
type KvstoredeleteBucketOKBody struct {

	// Result
	Result string `json:"result,omitempty"`
}

// Validate validates this kvstoredelete bucket o k body
func (o *KvstoredeleteBucketOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kvstoredelete bucket o k body based on context it is used
func (o *KvstoredeleteBucketOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *KvstoredeleteBucketOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *KvstoredeleteBucketOKBody) UnmarshalBinary(b []byte) error {
	var res KvstoredeleteBucketOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
