// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListVMInstanceTypesParams creates a new ListVMInstanceTypesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVMInstanceTypesParams() *ListVMInstanceTypesParams {
	return NewListVMInstanceTypesParamsWithTimeout(cr.DefaultTimeout)
}

// NewListVMInstanceTypesParamsWithTimeout creates a new ListVMInstanceTypesParams object
// with the ability to set a timeout on a request.
func NewListVMInstanceTypesParamsWithTimeout(timeout time.Duration) *ListVMInstanceTypesParams {
	return &ListVMInstanceTypesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListVMInstanceTypesParamsWithContext creates a new ListVMInstanceTypesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListVMInstanceTypesParams].
func NewListVMInstanceTypesParamsWithContext(ctx context.Context) *ListVMInstanceTypesParams {
	return &ListVMInstanceTypesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListVMInstanceTypesParamsWithHTTPClient creates a new ListVMInstanceTypesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVMInstanceTypesParamsWithHTTPClient(client *http.Client) *ListVMInstanceTypesParams {
	return &ListVMInstanceTypesParams{
		HTTPClient: client,
	}
}

/*
ListVMInstanceTypesParams contains all the parameters to send to the API endpoint

	for the list Vm instance types operation.

	Typically these are written to a http.Request.
*/
type ListVMInstanceTypesParams struct {

	/* Filter.

	   Filter the results based on criteria (e.g., CPU, memory).
	*/
	Filter *string

	/* SortBy.

	   Sort the list by a specific field (e.g., name, CPU count).
	*/
	SortBy *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list Vm instance types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMInstanceTypesParams) WithDefaults() *ListVMInstanceTypesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list Vm instance types params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMInstanceTypesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) WithTimeout(timeout time.Duration) *ListVMInstanceTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list Vm instance types params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListVMInstanceTypesParams].
func (o *ListVMInstanceTypesParams) WithContext(ctx context.Context) *ListVMInstanceTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list Vm instance types params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListVMInstanceTypesParams].
func (o *ListVMInstanceTypesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) WithHTTPClient(client *http.Client) *ListVMInstanceTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) WithFilter(filter *string) *ListVMInstanceTypesParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithSortBy adds the sortBy to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) WithSortBy(sortBy *string) *ListVMInstanceTypesParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the list Vm instance types params.
func (o *ListVMInstanceTypesParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListVMInstanceTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// query param sort-by
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sort-by", qSortBy); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
