// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ListUsersReader is a Reader for the ListUsers structure.
type ListUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListUsersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListUsersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListUsersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users] listUsers", response, response.Code())
	}
}

// NewListUsersOK creates a ListUsersOK with default headers values
func NewListUsersOK() *ListUsersOK {
	return &ListUsersOK{}
}

/*
ListUsersOK describes a response with status code 200, with default header values.

A successful response containing the list of users.
*/
type ListUsersOK struct {
	Payload []*ListUsersOKBodyItems0
}

// IsSuccess returns true when this list users o k response has a 2xx status code
func (o *ListUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list users o k response has a 3xx status code
func (o *ListUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list users o k response has a 4xx status code
func (o *ListUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list users o k response has a 5xx status code
func (o *ListUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list users o k response a status code equal to that given
func (o *ListUsersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list users o k response
func (o *ListUsersOK) Code() int {
	return 200
}

func (o *ListUsersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersOK %s", 200, payload)
}

func (o *ListUsersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersOK %s", 200, payload)
}

func (o *ListUsersOK) GetPayload() []*ListUsersOKBodyItems0 {
	return o.Payload
}

func (o *ListUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsersBadRequest creates a ListUsersBadRequest with default headers values
func NewListUsersBadRequest() *ListUsersBadRequest {
	return &ListUsersBadRequest{}
}

/*
ListUsersBadRequest describes a response with status code 400, with default header values.

Invalid request. Verify the tenant ID and format of the request.
*/
type ListUsersBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this list users bad request response has a 2xx status code
func (o *ListUsersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list users bad request response has a 3xx status code
func (o *ListUsersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list users bad request response has a 4xx status code
func (o *ListUsersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list users bad request response has a 5xx status code
func (o *ListUsersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list users bad request response a status code equal to that given
func (o *ListUsersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list users bad request response
func (o *ListUsersBadRequest) Code() int {
	return 400
}

func (o *ListUsersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersBadRequest %s", 400, payload)
}

func (o *ListUsersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersBadRequest %s", 400, payload)
}

func (o *ListUsersBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListUsersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsersUnauthorized creates a ListUsersUnauthorized with default headers values
func NewListUsersUnauthorized() *ListUsersUnauthorized {
	return &ListUsersUnauthorized{}
}

/*
ListUsersUnauthorized describes a response with status code 401, with default header values.

Authentication failed. Check username or password.
*/
type ListUsersUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this list users unauthorized response has a 2xx status code
func (o *ListUsersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list users unauthorized response has a 3xx status code
func (o *ListUsersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list users unauthorized response has a 4xx status code
func (o *ListUsersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list users unauthorized response has a 5xx status code
func (o *ListUsersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list users unauthorized response a status code equal to that given
func (o *ListUsersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list users unauthorized response
func (o *ListUsersUnauthorized) Code() int {
	return 401
}

func (o *ListUsersUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersUnauthorized %s", 401, payload)
}

func (o *ListUsersUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersUnauthorized %s", 401, payload)
}

func (o *ListUsersUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListUsersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListUsersInternalServerError creates a ListUsersInternalServerError with default headers values
func NewListUsersInternalServerError() *ListUsersInternalServerError {
	return &ListUsersInternalServerError{}
}

/*
ListUsersInternalServerError describes a response with status code 500, with default header values.

Internal server error. Please try again later.
*/
type ListUsersInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this list users internal server error response has a 2xx status code
func (o *ListUsersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list users internal server error response has a 3xx status code
func (o *ListUsersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list users internal server error response has a 4xx status code
func (o *ListUsersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list users internal server error response has a 5xx status code
func (o *ListUsersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list users internal server error response a status code equal to that given
func (o *ListUsersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list users internal server error response
func (o *ListUsersInternalServerError) Code() int {
	return 500
}

func (o *ListUsersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersInternalServerError %s", 500, payload)
}

func (o *ListUsersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users][%d] listUsersInternalServerError %s", 500, payload)
}

func (o *ListUsersInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListUsersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ListUsersOKBodyItems0 list users o k body items0
swagger:model ListUsersOKBodyItems0
*/
type ListUsersOKBodyItems0 struct {

	// Tags associated with the User
	Tags []string `json:"tags"`

	// The unique ID of the user
	UserID string `json:"user-id,omitempty"`

	// The username of the user
	Username string `json:"username,omitempty"`
}

// Validate validates this list users o k body items0
func (o *ListUsersOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list users o k body items0 based on context it is used
func (o *ListUsersOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListUsersOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListUsersOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListUsersOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
