// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListImagesParams creates a new ListImagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListImagesParams() *ListImagesParams {
	return NewListImagesParamsWithTimeout(cr.DefaultTimeout)
}

// NewListImagesParamsWithTimeout creates a new ListImagesParams object
// with the ability to set a timeout on a request.
func NewListImagesParamsWithTimeout(timeout time.Duration) *ListImagesParams {
	return &ListImagesParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListImagesParamsWithContext creates a new ListImagesParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListImagesParams].
func NewListImagesParamsWithContext(ctx context.Context) *ListImagesParams {
	return &ListImagesParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListImagesParamsWithHTTPClient creates a new ListImagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListImagesParamsWithHTTPClient(client *http.Client) *ListImagesParams {
	return &ListImagesParams{
		HTTPClient: client,
	}
}

/*
ListImagesParams contains all the parameters to send to the API endpoint

	for the list images operation.

	Typically these are written to a http.Request.
*/
type ListImagesParams struct {

	/* ImageID.

	   Filter images by unique ID.
	*/
	ImageID *string

	/* Name.

	   Filter images by name.
	*/
	Name *string

	/* OsName.

	   Filter images by operating system name.
	*/
	OsName *string

	/* OsVersion.

	   Filter images by operating system version.
	*/
	OsVersion *string

	/* Tag.

	   Filter images by a specific tag.
	*/
	Tag *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list images params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListImagesParams) WithDefaults() *ListImagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list images params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListImagesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list images params.
func (o *ListImagesParams) WithTimeout(timeout time.Duration) *ListImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list images params.
func (o *ListImagesParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list images params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListImagesParams].
func (o *ListImagesParams) WithContext(ctx context.Context) *ListImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list images params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListImagesParams].
func (o *ListImagesParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list images params.
func (o *ListImagesParams) WithHTTPClient(client *http.Client) *ListImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list images params.
func (o *ListImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageID adds the imageID to the list images params.
func (o *ListImagesParams) WithImageID(imageID *string) *ListImagesParams {
	o.SetImageID(imageID)
	return o
}

// SetImageID adds the imageId to the list images params.
func (o *ListImagesParams) SetImageID(imageID *string) {
	o.ImageID = imageID
}

// WithName adds the name to the list images params.
func (o *ListImagesParams) WithName(name *string) *ListImagesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list images params.
func (o *ListImagesParams) SetName(name *string) {
	o.Name = name
}

// WithOsName adds the osName to the list images params.
func (o *ListImagesParams) WithOsName(osName *string) *ListImagesParams {
	o.SetOsName(osName)
	return o
}

// SetOsName adds the osName to the list images params.
func (o *ListImagesParams) SetOsName(osName *string) {
	o.OsName = osName
}

// WithOsVersion adds the osVersion to the list images params.
func (o *ListImagesParams) WithOsVersion(osVersion *string) *ListImagesParams {
	o.SetOsVersion(osVersion)
	return o
}

// SetOsVersion adds the osVersion to the list images params.
func (o *ListImagesParams) SetOsVersion(osVersion *string) {
	o.OsVersion = osVersion
}

// WithTag adds the tag to the list images params.
func (o *ListImagesParams) WithTag(tag *string) *ListImagesParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the list images params.
func (o *ListImagesParams) SetTag(tag *string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImageID != nil {

		// query param image-id
		var qrImageID string

		if o.ImageID != nil {
			qrImageID = *o.ImageID
		}
		qImageID := qrImageID
		if qImageID != "" {

			if err := r.SetQueryParam("image-id", qImageID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.OsName != nil {

		// query param os-name
		var qrOsName string

		if o.OsName != nil {
			qrOsName = *o.OsName
		}
		qOsName := qrOsName
		if qOsName != "" {

			if err := r.SetQueryParam("os-name", qOsName); err != nil {
				return err
			}
		}
	}

	if o.OsVersion != nil {

		// query param os-version
		var qrOsVersion string

		if o.OsVersion != nil {
			qrOsVersion = *o.OsVersion
		}
		qOsVersion := qrOsVersion
		if qOsVersion != "" {

			if err := r.SetQueryParam("os-version", qOsVersion); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// query param tag
		var qrTag string

		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {

			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
