// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ListServiceAccountsReader is a Reader for the ListServiceAccounts structure.
type ListServiceAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServiceAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListServiceAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListServiceAccountsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListServiceAccountsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListServiceAccountsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /roles/service-accounts] listServiceAccounts", response, response.Code())
	}
}

// NewListServiceAccountsOK creates a ListServiceAccountsOK with default headers values
func NewListServiceAccountsOK() *ListServiceAccountsOK {
	return &ListServiceAccountsOK{}
}

/*
ListServiceAccountsOK describes a response with status code 200, with default header values.

A successful response with the list of Service Accounts.
*/
type ListServiceAccountsOK struct {
	Payload []*ListServiceAccountsOKBodyItems0
}

// IsSuccess returns true when this list service accounts o k response has a 2xx status code
func (o *ListServiceAccountsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list service accounts o k response has a 3xx status code
func (o *ListServiceAccountsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list service accounts o k response has a 4xx status code
func (o *ListServiceAccountsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list service accounts o k response has a 5xx status code
func (o *ListServiceAccountsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list service accounts o k response a status code equal to that given
func (o *ListServiceAccountsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list service accounts o k response
func (o *ListServiceAccountsOK) Code() int {
	return 200
}

func (o *ListServiceAccountsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsOK %s", 200, payload)
}

func (o *ListServiceAccountsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsOK %s", 200, payload)
}

func (o *ListServiceAccountsOK) GetPayload() []*ListServiceAccountsOKBodyItems0 {
	return o.Payload
}

func (o *ListServiceAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListServiceAccountsBadRequest creates a ListServiceAccountsBadRequest with default headers values
func NewListServiceAccountsBadRequest() *ListServiceAccountsBadRequest {
	return &ListServiceAccountsBadRequest{}
}

/*
ListServiceAccountsBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ListServiceAccountsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this list service accounts bad request response has a 2xx status code
func (o *ListServiceAccountsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list service accounts bad request response has a 3xx status code
func (o *ListServiceAccountsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list service accounts bad request response has a 4xx status code
func (o *ListServiceAccountsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list service accounts bad request response has a 5xx status code
func (o *ListServiceAccountsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list service accounts bad request response a status code equal to that given
func (o *ListServiceAccountsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list service accounts bad request response
func (o *ListServiceAccountsBadRequest) Code() int {
	return 400
}

func (o *ListServiceAccountsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsBadRequest %s", 400, payload)
}

func (o *ListServiceAccountsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsBadRequest %s", 400, payload)
}

func (o *ListServiceAccountsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceAccountsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListServiceAccountsUnauthorized creates a ListServiceAccountsUnauthorized with default headers values
func NewListServiceAccountsUnauthorized() *ListServiceAccountsUnauthorized {
	return &ListServiceAccountsUnauthorized{}
}

/*
ListServiceAccountsUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type ListServiceAccountsUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this list service accounts unauthorized response has a 2xx status code
func (o *ListServiceAccountsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list service accounts unauthorized response has a 3xx status code
func (o *ListServiceAccountsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list service accounts unauthorized response has a 4xx status code
func (o *ListServiceAccountsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list service accounts unauthorized response has a 5xx status code
func (o *ListServiceAccountsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list service accounts unauthorized response a status code equal to that given
func (o *ListServiceAccountsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list service accounts unauthorized response
func (o *ListServiceAccountsUnauthorized) Code() int {
	return 401
}

func (o *ListServiceAccountsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsUnauthorized %s", 401, payload)
}

func (o *ListServiceAccountsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsUnauthorized %s", 401, payload)
}

func (o *ListServiceAccountsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceAccountsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListServiceAccountsInternalServerError creates a ListServiceAccountsInternalServerError with default headers values
func NewListServiceAccountsInternalServerError() *ListServiceAccountsInternalServerError {
	return &ListServiceAccountsInternalServerError{}
}

/*
ListServiceAccountsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type ListServiceAccountsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this list service accounts internal server error response has a 2xx status code
func (o *ListServiceAccountsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list service accounts internal server error response has a 3xx status code
func (o *ListServiceAccountsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list service accounts internal server error response has a 4xx status code
func (o *ListServiceAccountsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list service accounts internal server error response has a 5xx status code
func (o *ListServiceAccountsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list service accounts internal server error response a status code equal to that given
func (o *ListServiceAccountsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list service accounts internal server error response
func (o *ListServiceAccountsInternalServerError) Code() int {
	return 500
}

func (o *ListServiceAccountsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsInternalServerError %s", 500, payload)
}

func (o *ListServiceAccountsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/service-accounts][%d] listServiceAccountsInternalServerError %s", 500, payload)
}

func (o *ListServiceAccountsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListServiceAccountsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ListServiceAccountsOKBodyItems0 list service accounts o k body items0
swagger:model ListServiceAccountsOKBodyItems0
*/
type ListServiceAccountsOKBodyItems0 struct {

	// Number of active instance bindings
	ActiveInstancesCount int64 `json:"active_instances_count,omitempty"`

	// Number of roles assigned to this Service Account
	AttachedRolesCount int64 `json:"attached_roles_count,omitempty"`

	// Timestamp when the Service Account was created, in RFC3339 format.
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Description of the Service Account
	Description string `json:"description,omitempty"`

	// Name of the Service Account
	Name string `json:"name,omitempty"`
}

// Validate validates this list service accounts o k body items0
func (o *ListServiceAccountsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListServiceAccountsOKBodyItems0) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this list service accounts o k body items0 based on context it is used
func (o *ListServiceAccountsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListServiceAccountsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListServiceAccountsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListServiceAccountsOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
