// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ListVMInstanceTypesReader is a Reader for the ListVMInstanceTypes structure.
type ListVMInstanceTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVMInstanceTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListVMInstanceTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListVMInstanceTypesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /compute/vms/instance-types] listVmInstanceTypes", response, response.Code())
	}
}

// NewListVMInstanceTypesOK creates a ListVMInstanceTypesOK with default headers values
func NewListVMInstanceTypesOK() *ListVMInstanceTypesOK {
	return &ListVMInstanceTypesOK{}
}

/*
ListVMInstanceTypesOK describes a response with status code 200, with default header values.

A successful response
*/
type ListVMInstanceTypesOK struct {
	Payload []*ListVMInstanceTypesOKBodyItems0
}

// IsSuccess returns true when this list Vm instance types o k response has a 2xx status code
func (o *ListVMInstanceTypesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list Vm instance types o k response has a 3xx status code
func (o *ListVMInstanceTypesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Vm instance types o k response has a 4xx status code
func (o *ListVMInstanceTypesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list Vm instance types o k response has a 5xx status code
func (o *ListVMInstanceTypesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list Vm instance types o k response a status code equal to that given
func (o *ListVMInstanceTypesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list Vm instance types o k response
func (o *ListVMInstanceTypesOK) Code() int {
	return 200
}

func (o *ListVMInstanceTypesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compute/vms/instance-types][%d] listVmInstanceTypesOK %s", 200, payload)
}

func (o *ListVMInstanceTypesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compute/vms/instance-types][%d] listVmInstanceTypesOK %s", 200, payload)
}

func (o *ListVMInstanceTypesOK) GetPayload() []*ListVMInstanceTypesOKBodyItems0 {
	return o.Payload
}

func (o *ListVMInstanceTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListVMInstanceTypesBadRequest creates a ListVMInstanceTypesBadRequest with default headers values
func NewListVMInstanceTypesBadRequest() *ListVMInstanceTypesBadRequest {
	return &ListVMInstanceTypesBadRequest{}
}

/*
ListVMInstanceTypesBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ListVMInstanceTypesBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this list Vm instance types bad request response has a 2xx status code
func (o *ListVMInstanceTypesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list Vm instance types bad request response has a 3xx status code
func (o *ListVMInstanceTypesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list Vm instance types bad request response has a 4xx status code
func (o *ListVMInstanceTypesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list Vm instance types bad request response has a 5xx status code
func (o *ListVMInstanceTypesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list Vm instance types bad request response a status code equal to that given
func (o *ListVMInstanceTypesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list Vm instance types bad request response
func (o *ListVMInstanceTypesBadRequest) Code() int {
	return 400
}

func (o *ListVMInstanceTypesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compute/vms/instance-types][%d] listVmInstanceTypesBadRequest %s", 400, payload)
}

func (o *ListVMInstanceTypesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /compute/vms/instance-types][%d] listVmInstanceTypesBadRequest %s", 400, payload)
}

func (o *ListVMInstanceTypesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListVMInstanceTypesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ListVMInstanceTypesOKBodyItems0 list VM instance types o k body items0
swagger:model ListVMInstanceTypesOKBodyItems0
*/
type ListVMInstanceTypesOKBodyItems0 struct {

	// Number of CPUs for the instance type
	CPUCount int64 `json:"cpu_count,omitempty"`

	// Additional description of the instance type
	Description string `json:"description,omitempty"`

	// Disk size in GB for the instance type
	DiskGb int64 `json:"disk_gb,omitempty"`

	// Amount of memory in MB for the instance type
	MemoryMb int64 `json:"memory_mb,omitempty"`

	// Name of the instance type
	Name string `json:"name,omitempty"`
}

// Validate validates this list VM instance types o k body items0
func (o *ListVMInstanceTypesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list VM instance types o k body items0 based on context it is used
func (o *ListVMInstanceTypesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListVMInstanceTypesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListVMInstanceTypesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListVMInstanceTypesOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
