// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ListPredefinedRolesReader is a Reader for the ListPredefinedRoles structure.
type ListPredefinedRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPredefinedRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListPredefinedRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListPredefinedRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListPredefinedRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListPredefinedRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /roles/predefined] listPredefinedRoles", response, response.Code())
	}
}

// NewListPredefinedRolesOK creates a ListPredefinedRolesOK with default headers values
func NewListPredefinedRolesOK() *ListPredefinedRolesOK {
	return &ListPredefinedRolesOK{}
}

/*
ListPredefinedRolesOK describes a response with status code 200, with default header values.

A successful response with the list of predefined roles.
*/
type ListPredefinedRolesOK struct {
	Payload []*ListPredefinedRolesOKBodyItems0
}

// IsSuccess returns true when this list predefined roles o k response has a 2xx status code
func (o *ListPredefinedRolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list predefined roles o k response has a 3xx status code
func (o *ListPredefinedRolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list predefined roles o k response has a 4xx status code
func (o *ListPredefinedRolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list predefined roles o k response has a 5xx status code
func (o *ListPredefinedRolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list predefined roles o k response a status code equal to that given
func (o *ListPredefinedRolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list predefined roles o k response
func (o *ListPredefinedRolesOK) Code() int {
	return 200
}

func (o *ListPredefinedRolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesOK %s", 200, payload)
}

func (o *ListPredefinedRolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesOK %s", 200, payload)
}

func (o *ListPredefinedRolesOK) GetPayload() []*ListPredefinedRolesOKBodyItems0 {
	return o.Payload
}

func (o *ListPredefinedRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPredefinedRolesBadRequest creates a ListPredefinedRolesBadRequest with default headers values
func NewListPredefinedRolesBadRequest() *ListPredefinedRolesBadRequest {
	return &ListPredefinedRolesBadRequest{}
}

/*
ListPredefinedRolesBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ListPredefinedRolesBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this list predefined roles bad request response has a 2xx status code
func (o *ListPredefinedRolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list predefined roles bad request response has a 3xx status code
func (o *ListPredefinedRolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list predefined roles bad request response has a 4xx status code
func (o *ListPredefinedRolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list predefined roles bad request response has a 5xx status code
func (o *ListPredefinedRolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list predefined roles bad request response a status code equal to that given
func (o *ListPredefinedRolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list predefined roles bad request response
func (o *ListPredefinedRolesBadRequest) Code() int {
	return 400
}

func (o *ListPredefinedRolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesBadRequest %s", 400, payload)
}

func (o *ListPredefinedRolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesBadRequest %s", 400, payload)
}

func (o *ListPredefinedRolesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListPredefinedRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPredefinedRolesUnauthorized creates a ListPredefinedRolesUnauthorized with default headers values
func NewListPredefinedRolesUnauthorized() *ListPredefinedRolesUnauthorized {
	return &ListPredefinedRolesUnauthorized{}
}

/*
ListPredefinedRolesUnauthorized describes a response with status code 401, with default header values.

Authentication failed.
*/
type ListPredefinedRolesUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this list predefined roles unauthorized response has a 2xx status code
func (o *ListPredefinedRolesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list predefined roles unauthorized response has a 3xx status code
func (o *ListPredefinedRolesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list predefined roles unauthorized response has a 4xx status code
func (o *ListPredefinedRolesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list predefined roles unauthorized response has a 5xx status code
func (o *ListPredefinedRolesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list predefined roles unauthorized response a status code equal to that given
func (o *ListPredefinedRolesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list predefined roles unauthorized response
func (o *ListPredefinedRolesUnauthorized) Code() int {
	return 401
}

func (o *ListPredefinedRolesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesUnauthorized %s", 401, payload)
}

func (o *ListPredefinedRolesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesUnauthorized %s", 401, payload)
}

func (o *ListPredefinedRolesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListPredefinedRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPredefinedRolesInternalServerError creates a ListPredefinedRolesInternalServerError with default headers values
func NewListPredefinedRolesInternalServerError() *ListPredefinedRolesInternalServerError {
	return &ListPredefinedRolesInternalServerError{}
}

/*
ListPredefinedRolesInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type ListPredefinedRolesInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this list predefined roles internal server error response has a 2xx status code
func (o *ListPredefinedRolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list predefined roles internal server error response has a 3xx status code
func (o *ListPredefinedRolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list predefined roles internal server error response has a 4xx status code
func (o *ListPredefinedRolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list predefined roles internal server error response has a 5xx status code
func (o *ListPredefinedRolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list predefined roles internal server error response a status code equal to that given
func (o *ListPredefinedRolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list predefined roles internal server error response
func (o *ListPredefinedRolesInternalServerError) Code() int {
	return 500
}

func (o *ListPredefinedRolesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesInternalServerError %s", 500, payload)
}

func (o *ListPredefinedRolesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /roles/predefined][%d] listPredefinedRolesInternalServerError %s", 500, payload)
}

func (o *ListPredefinedRolesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListPredefinedRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ListPredefinedRolesOKBodyItems0 list predefined roles o k body items0
swagger:model ListPredefinedRolesOKBodyItems0
*/
type ListPredefinedRolesOKBodyItems0 struct {

	// Description of the predefined role
	Description string `json:"description,omitempty"`

	// Number of flattened (effective) permission entries
	EffectivePermissionsCount int64 `json:"effective_permissions_count,omitempty"`

	// Module this role applies to (base for core roles, or domain-specific)
	Module string `json:"module,omitempty"`

	// The role name (e.g., Owner, Editor, Viewer)
	Name string `json:"name,omitempty"`

	// Number of granted granular permissions
	PermissionsCount int64 `json:"permissions_count,omitempty"`
}

// Validate validates this list predefined roles o k body items0
func (o *ListPredefinedRolesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list predefined roles o k body items0 based on context it is used
func (o *ListPredefinedRolesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListPredefinedRolesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListPredefinedRolesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListPredefinedRolesOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
