// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListRoleCompositionParams creates a new ListRoleCompositionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListRoleCompositionParams() *ListRoleCompositionParams {
	return NewListRoleCompositionParamsWithTimeout(cr.DefaultTimeout)
}

// NewListRoleCompositionParamsWithTimeout creates a new ListRoleCompositionParams object
// with the ability to set a timeout on a request.
func NewListRoleCompositionParamsWithTimeout(timeout time.Duration) *ListRoleCompositionParams {
	return &ListRoleCompositionParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListRoleCompositionParamsWithContext creates a new ListRoleCompositionParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListRoleCompositionParams].
func NewListRoleCompositionParamsWithContext(ctx context.Context) *ListRoleCompositionParams {
	return &ListRoleCompositionParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListRoleCompositionParamsWithHTTPClient creates a new ListRoleCompositionParams object
// with the ability to set a custom HTTPClient for a request.
func NewListRoleCompositionParamsWithHTTPClient(client *http.Client) *ListRoleCompositionParams {
	return &ListRoleCompositionParams{
		HTTPClient: client,
	}
}

/*
ListRoleCompositionParams contains all the parameters to send to the API endpoint

	for the list role composition operation.

	Typically these are written to a http.Request.
*/
type ListRoleCompositionParams struct {

	/* Role.

	   Name of the role to inspect composition for. Returns an empty list for leaf roles.
	*/
	Role string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list role composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleCompositionParams) WithDefaults() *ListRoleCompositionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list role composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListRoleCompositionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list role composition params.
func (o *ListRoleCompositionParams) WithTimeout(timeout time.Duration) *ListRoleCompositionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list role composition params.
func (o *ListRoleCompositionParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list role composition params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListRoleCompositionParams].
func (o *ListRoleCompositionParams) WithContext(ctx context.Context) *ListRoleCompositionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list role composition params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListRoleCompositionParams].
func (o *ListRoleCompositionParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list role composition params.
func (o *ListRoleCompositionParams) WithHTTPClient(client *http.Client) *ListRoleCompositionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list role composition params.
func (o *ListRoleCompositionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the list role composition params.
func (o *ListRoleCompositionParams) WithRole(role string) *ListRoleCompositionParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the list role composition params.
func (o *ListRoleCompositionParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListRoleCompositionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
