// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewListNetworksParams creates a new ListNetworksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListNetworksParams() *ListNetworksParams {
	return NewListNetworksParamsWithTimeout(cr.DefaultTimeout)
}

// NewListNetworksParamsWithTimeout creates a new ListNetworksParams object
// with the ability to set a timeout on a request.
func NewListNetworksParamsWithTimeout(timeout time.Duration) *ListNetworksParams {
	return &ListNetworksParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListNetworksParamsWithContext creates a new ListNetworksParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNetworksParams].
func NewListNetworksParamsWithContext(ctx context.Context) *ListNetworksParams {
	return &ListNetworksParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListNetworksParamsWithHTTPClient creates a new ListNetworksParams object
// with the ability to set a custom HTTPClient for a request.
func NewListNetworksParamsWithHTTPClient(client *http.Client) *ListNetworksParams {
	return &ListNetworksParams{
		HTTPClient: client,
	}
}

/*
ListNetworksParams contains all the parameters to send to the API endpoint

	for the list networks operation.

	Typically these are written to a http.Request.
*/
type ListNetworksParams struct {

	/* Filter.

	   Apply a filter to narrow down the list of networks. Filters can be applied on properties like ID, name, status, etc.
	*/
	Filter *string

	/* Limit.

	   Limit the number of networks displayed.
	*/
	Limit *int64

	/* Quiet.

	   Suppress normal output; only display network IDs.
	*/
	Quiet *bool

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list networks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNetworksParams) WithDefaults() *ListNetworksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list networks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNetworksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list networks params.
func (o *ListNetworksParams) WithTimeout(timeout time.Duration) *ListNetworksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list networks params.
func (o *ListNetworksParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list networks params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNetworksParams].
func (o *ListNetworksParams) WithContext(ctx context.Context) *ListNetworksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list networks params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNetworksParams].
func (o *ListNetworksParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list networks params.
func (o *ListNetworksParams) WithHTTPClient(client *http.Client) *ListNetworksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list networks params.
func (o *ListNetworksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the list networks params.
func (o *ListNetworksParams) WithFilter(filter *string) *ListNetworksParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the list networks params.
func (o *ListNetworksParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithLimit adds the limit to the list networks params.
func (o *ListNetworksParams) WithLimit(limit *int64) *ListNetworksParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list networks params.
func (o *ListNetworksParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithQuiet adds the quiet to the list networks params.
func (o *ListNetworksParams) WithQuiet(quiet *bool) *ListNetworksParams {
	o.SetQuiet(quiet)
	return o
}

// SetQuiet adds the quiet to the list networks params.
func (o *ListNetworksParams) SetQuiet(quiet *bool) {
	o.Quiet = quiet
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListNetworksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := conv.FormatInteger(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Quiet != nil {

		// query param quiet
		var qrQuiet bool

		if o.Quiet != nil {
			qrQuiet = *o.Quiet
		}
		qQuiet := conv.FormatBool(qrQuiet)
		if qQuiet != "" {

			if err := r.SetQueryParam("quiet", qQuiet); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
