// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLockUserParams creates a new LockUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLockUserParams() *LockUserParams {
	return NewLockUserParamsWithTimeout(cr.DefaultTimeout)
}

// NewLockUserParamsWithTimeout creates a new LockUserParams object
// with the ability to set a timeout on a request.
func NewLockUserParamsWithTimeout(timeout time.Duration) *LockUserParams {
	return &LockUserParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewLockUserParamsWithContext creates a new LockUserParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [LockUserParams].
func NewLockUserParamsWithContext(ctx context.Context) *LockUserParams {
	return &LockUserParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewLockUserParamsWithHTTPClient creates a new LockUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewLockUserParamsWithHTTPClient(client *http.Client) *LockUserParams {
	return &LockUserParams{
		HTTPClient: client,
	}
}

/*
LockUserParams contains all the parameters to send to the API endpoint

	for the lock user operation.

	Typically these are written to a http.Request.
*/
type LockUserParams struct {

	/* UserID.

	   Unique ID of the user account to lock (required).
	*/
	UserID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the lock user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LockUserParams) WithDefaults() *LockUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lock user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LockUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lock user params.
func (o *LockUserParams) WithTimeout(timeout time.Duration) *LockUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lock user params.
func (o *LockUserParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the lock user params.
//
// Deprecated: use the operation call with context to pass the context instead of [LockUserParams].
func (o *LockUserParams) WithContext(ctx context.Context) *LockUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lock user params.
//
// Deprecated: use the operation call with context to pass the context instead of [LockUserParams].
func (o *LockUserParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the lock user params.
func (o *LockUserParams) WithHTTPClient(client *http.Client) *LockUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lock user params.
func (o *LockUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the lock user params.
func (o *LockUserParams) WithUserID(userID string) *LockUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the lock user params.
func (o *LockUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *LockUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param user-id
	if err := r.SetPathParam("user-id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
