// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMetadatamanagerGetParams creates a new MetadatamanagerGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMetadatamanagerGetParams() *MetadatamanagerGetParams {
	return NewMetadatamanagerGetParamsWithTimeout(cr.DefaultTimeout)
}

// NewMetadatamanagerGetParamsWithTimeout creates a new MetadatamanagerGetParams object
// with the ability to set a timeout on a request.
func NewMetadatamanagerGetParamsWithTimeout(timeout time.Duration) *MetadatamanagerGetParams {
	return &MetadatamanagerGetParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewMetadatamanagerGetParamsWithContext creates a new MetadatamanagerGetParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [MetadatamanagerGetParams].
func NewMetadatamanagerGetParamsWithContext(ctx context.Context) *MetadatamanagerGetParams {
	return &MetadatamanagerGetParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewMetadatamanagerGetParamsWithHTTPClient creates a new MetadatamanagerGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewMetadatamanagerGetParamsWithHTTPClient(client *http.Client) *MetadatamanagerGetParams {
	return &MetadatamanagerGetParams{
		HTTPClient: client,
	}
}

/*
MetadatamanagerGetParams contains all the parameters to send to the API endpoint

	for the metadatamanager get operation.

	Typically these are written to a http.Request.
*/
type MetadatamanagerGetParams struct {

	/* ID.

	   Resource id (e.g vol-414741c9)
	*/
	ID string

	/* Type.

	   Entity type (instance, volume, etc)
	*/
	Type *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the metadatamanager get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetadatamanagerGetParams) WithDefaults() *MetadatamanagerGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the metadatamanager get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetadatamanagerGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the metadatamanager get params.
func (o *MetadatamanagerGetParams) WithTimeout(timeout time.Duration) *MetadatamanagerGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metadatamanager get params.
func (o *MetadatamanagerGetParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the metadatamanager get params.
//
// Deprecated: use the operation call with context to pass the context instead of [MetadatamanagerGetParams].
func (o *MetadatamanagerGetParams) WithContext(ctx context.Context) *MetadatamanagerGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metadatamanager get params.
//
// Deprecated: use the operation call with context to pass the context instead of [MetadatamanagerGetParams].
func (o *MetadatamanagerGetParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the metadatamanager get params.
func (o *MetadatamanagerGetParams) WithHTTPClient(client *http.Client) *MetadatamanagerGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metadatamanager get params.
func (o *MetadatamanagerGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the metadatamanager get params.
func (o *MetadatamanagerGetParams) WithID(id string) *MetadatamanagerGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the metadatamanager get params.
func (o *MetadatamanagerGetParams) SetID(id string) {
	o.ID = id
}

// WithType adds the typeVar to the metadatamanager get params.
func (o *MetadatamanagerGetParams) WithType(typeVar *string) *MetadatamanagerGetParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the metadatamanager get params.
func (o *MetadatamanagerGetParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *MetadatamanagerGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
