// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ModifyTenantReader is a Reader for the ModifyTenant structure.
type ModifyTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewModifyTenantAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewModifyTenantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /tenants/{tenant-id}] modifyTenant", response, response.Code())
	}
}

// NewModifyTenantAccepted creates a ModifyTenantAccepted with default headers values
func NewModifyTenantAccepted() *ModifyTenantAccepted {
	return &ModifyTenantAccepted{}
}

/*
ModifyTenantAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for tenant modification
*/
type ModifyTenantAccepted struct {
	Payload *ModifyTenantAcceptedBody
}

// IsSuccess returns true when this modify tenant accepted response has a 2xx status code
func (o *ModifyTenantAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify tenant accepted response has a 3xx status code
func (o *ModifyTenantAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify tenant accepted response has a 4xx status code
func (o *ModifyTenantAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify tenant accepted response has a 5xx status code
func (o *ModifyTenantAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this modify tenant accepted response a status code equal to that given
func (o *ModifyTenantAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the modify tenant accepted response
func (o *ModifyTenantAccepted) Code() int {
	return 202
}

func (o *ModifyTenantAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /tenants/{tenant-id}][%d] modifyTenantAccepted %s", 202, payload)
}

func (o *ModifyTenantAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /tenants/{tenant-id}][%d] modifyTenantAccepted %s", 202, payload)
}

func (o *ModifyTenantAccepted) GetPayload() *ModifyTenantAcceptedBody {
	return o.Payload
}

func (o *ModifyTenantAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ModifyTenantAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewModifyTenantBadRequest creates a ModifyTenantBadRequest with default headers values
func NewModifyTenantBadRequest() *ModifyTenantBadRequest {
	return &ModifyTenantBadRequest{}
}

/*
ModifyTenantBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ModifyTenantBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this modify tenant bad request response has a 2xx status code
func (o *ModifyTenantBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this modify tenant bad request response has a 3xx status code
func (o *ModifyTenantBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify tenant bad request response has a 4xx status code
func (o *ModifyTenantBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this modify tenant bad request response has a 5xx status code
func (o *ModifyTenantBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this modify tenant bad request response a status code equal to that given
func (o *ModifyTenantBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the modify tenant bad request response
func (o *ModifyTenantBadRequest) Code() int {
	return 400
}

func (o *ModifyTenantBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /tenants/{tenant-id}][%d] modifyTenantBadRequest %s", 400, payload)
}

func (o *ModifyTenantBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /tenants/{tenant-id}][%d] modifyTenantBadRequest %s", 400, payload)
}

func (o *ModifyTenantBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ModifyTenantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ModifyTenantAcceptedBody modify tenant accepted body
swagger:model ModifyTenantAcceptedBody
*/
type ModifyTenantAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this modify tenant accepted body
func (o *ModifyTenantAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyTenantAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("modifyTenantAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var modifyTenantAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		modifyTenantAcceptedBodyTypeStatusPropEnum = append(modifyTenantAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// ModifyTenantAcceptedBodyStatusAccepted captures enum value "accepted"
	ModifyTenantAcceptedBodyStatusAccepted string = "accepted"

	// ModifyTenantAcceptedBodyStatusCompleted captures enum value "completed"
	ModifyTenantAcceptedBodyStatusCompleted string = "completed"

	// ModifyTenantAcceptedBodyStatusFailed captures enum value "failed"
	ModifyTenantAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *ModifyTenantAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, modifyTenantAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *ModifyTenantAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("modifyTenantAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *ModifyTenantAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("modifyTenantAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this modify tenant accepted body based on context it is used
func (o *ModifyTenantAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ModifyTenantAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyTenantAcceptedBody) UnmarshalBinary(b []byte) error {
	var res ModifyTenantAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
