// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostHelloParams creates a new PostHelloParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostHelloParams() *PostHelloParams {
	return NewPostHelloParamsWithTimeout(cr.DefaultTimeout)
}

// NewPostHelloParamsWithTimeout creates a new PostHelloParams object
// with the ability to set a timeout on a request.
func NewPostHelloParamsWithTimeout(timeout time.Duration) *PostHelloParams {
	return &PostHelloParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewPostHelloParamsWithContext creates a new PostHelloParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [PostHelloParams].
func NewPostHelloParamsWithContext(ctx context.Context) *PostHelloParams {
	return &PostHelloParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewPostHelloParamsWithHTTPClient creates a new PostHelloParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostHelloParamsWithHTTPClient(client *http.Client) *PostHelloParams {
	return &PostHelloParams{
		HTTPClient: client,
	}
}

/*
PostHelloParams contains all the parameters to send to the API endpoint

	for the post hello operation.

	Typically these are written to a http.Request.
*/
type PostHelloParams struct {

	/* Message.

	   Hello message to be posted
	*/
	Message string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the post hello params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHelloParams) WithDefaults() *PostHelloParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post hello params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHelloParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post hello params.
func (o *PostHelloParams) WithTimeout(timeout time.Duration) *PostHelloParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post hello params.
func (o *PostHelloParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the post hello params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostHelloParams].
func (o *PostHelloParams) WithContext(ctx context.Context) *PostHelloParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post hello params.
//
// Deprecated: use the operation call with context to pass the context instead of [PostHelloParams].
func (o *PostHelloParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the post hello params.
func (o *PostHelloParams) WithHTTPClient(client *http.Client) *PostHelloParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post hello params.
func (o *PostHelloParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMessage adds the message to the post hello params.
func (o *PostHelloParams) WithMessage(message string) *PostHelloParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the post hello params.
func (o *PostHelloParams) SetMessage(message string) {
	o.Message = message
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *PostHelloParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// form param message
	frMessage := o.Message
	fMessage := frMessage
	if fMessage != "" {
		if err := r.SetFormParam("message", fMessage); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
