// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// PostHelloReader is a Reader for the PostHello structure.
type PostHelloReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHelloReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewPostHelloAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostHelloBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostHelloUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostHelloInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /hello] postHello", response, response.Code())
	}
}

// NewPostHelloAccepted creates a PostHelloAccepted with default headers values
func NewPostHelloAccepted() *PostHelloAccepted {
	return &PostHelloAccepted{}
}

/*
PostHelloAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for hello message.
*/
type PostHelloAccepted struct {
	Payload *PostHelloAcceptedBody
}

// IsSuccess returns true when this post hello accepted response has a 2xx status code
func (o *PostHelloAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post hello accepted response has a 3xx status code
func (o *PostHelloAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post hello accepted response has a 4xx status code
func (o *PostHelloAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this post hello accepted response has a 5xx status code
func (o *PostHelloAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this post hello accepted response a status code equal to that given
func (o *PostHelloAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the post hello accepted response
func (o *PostHelloAccepted) Code() int {
	return 202
}

func (o *PostHelloAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloAccepted %s", 202, payload)
}

func (o *PostHelloAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloAccepted %s", 202, payload)
}

func (o *PostHelloAccepted) GetPayload() *PostHelloAcceptedBody {
	return o.Payload
}

func (o *PostHelloAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostHelloAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostHelloBadRequest creates a PostHelloBadRequest with default headers values
func NewPostHelloBadRequest() *PostHelloBadRequest {
	return &PostHelloBadRequest{}
}

/*
PostHelloBadRequest describes a response with status code 400, with default header values.

Invalid request due to malformed data.
*/
type PostHelloBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post hello bad request response has a 2xx status code
func (o *PostHelloBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post hello bad request response has a 3xx status code
func (o *PostHelloBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post hello bad request response has a 4xx status code
func (o *PostHelloBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post hello bad request response has a 5xx status code
func (o *PostHelloBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post hello bad request response a status code equal to that given
func (o *PostHelloBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post hello bad request response
func (o *PostHelloBadRequest) Code() int {
	return 400
}

func (o *PostHelloBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloBadRequest %s", 400, payload)
}

func (o *PostHelloBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloBadRequest %s", 400, payload)
}

func (o *PostHelloBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostHelloBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostHelloUnauthorized creates a PostHelloUnauthorized with default headers values
func NewPostHelloUnauthorized() *PostHelloUnauthorized {
	return &PostHelloUnauthorized{}
}

/*
PostHelloUnauthorized describes a response with status code 401, with default header values.

Incorrect username or password.
*/
type PostHelloUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this post hello unauthorized response has a 2xx status code
func (o *PostHelloUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post hello unauthorized response has a 3xx status code
func (o *PostHelloUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post hello unauthorized response has a 4xx status code
func (o *PostHelloUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post hello unauthorized response has a 5xx status code
func (o *PostHelloUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post hello unauthorized response a status code equal to that given
func (o *PostHelloUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post hello unauthorized response
func (o *PostHelloUnauthorized) Code() int {
	return 401
}

func (o *PostHelloUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloUnauthorized %s", 401, payload)
}

func (o *PostHelloUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloUnauthorized %s", 401, payload)
}

func (o *PostHelloUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostHelloUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostHelloInternalServerError creates a PostHelloInternalServerError with default headers values
func NewPostHelloInternalServerError() *PostHelloInternalServerError {
	return &PostHelloInternalServerError{}
}

/*
PostHelloInternalServerError describes a response with status code 500, with default header values.

Internal server error occurred.
*/
type PostHelloInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post hello internal server error response has a 2xx status code
func (o *PostHelloInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post hello internal server error response has a 3xx status code
func (o *PostHelloInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post hello internal server error response has a 4xx status code
func (o *PostHelloInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post hello internal server error response has a 5xx status code
func (o *PostHelloInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post hello internal server error response a status code equal to that given
func (o *PostHelloInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post hello internal server error response
func (o *PostHelloInternalServerError) Code() int {
	return 500
}

func (o *PostHelloInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloInternalServerError %s", 500, payload)
}

func (o *PostHelloInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /hello][%d] postHelloInternalServerError %s", 500, payload)
}

func (o *PostHelloInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostHelloInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
PostHelloAcceptedBody post hello accepted body
swagger:model PostHelloAcceptedBody
*/
type PostHelloAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this post hello accepted body
func (o *PostHelloAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostHelloAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("postHelloAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var postHelloAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postHelloAcceptedBodyTypeStatusPropEnum = append(postHelloAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// PostHelloAcceptedBodyStatusAccepted captures enum value "accepted"
	PostHelloAcceptedBodyStatusAccepted string = "accepted"

	// PostHelloAcceptedBodyStatusCompleted captures enum value "completed"
	PostHelloAcceptedBodyStatusCompleted string = "completed"

	// PostHelloAcceptedBodyStatusFailed captures enum value "failed"
	PostHelloAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *PostHelloAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postHelloAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostHelloAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("postHelloAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *PostHelloAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("postHelloAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post hello accepted body based on context it is used
func (o *PostHelloAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostHelloAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostHelloAcceptedBody) UnmarshalBinary(b []byte) error {
	var res PostHelloAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
