// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// RebootVMReader is a Reader for the RebootVM structure.
type RebootVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RebootVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewRebootVMAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRebootVMBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /compute/vms/{instance-id}] rebootVm", response, response.Code())
	}
}

// NewRebootVMAccepted creates a RebootVMAccepted with default headers values
func NewRebootVMAccepted() *RebootVMAccepted {
	return &RebootVMAccepted{}
}

/*
RebootVMAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for VM reboot
*/
type RebootVMAccepted struct {
	Payload *RebootVMAcceptedBody
}

// IsSuccess returns true when this reboot Vm accepted response has a 2xx status code
func (o *RebootVMAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this reboot Vm accepted response has a 3xx status code
func (o *RebootVMAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reboot Vm accepted response has a 4xx status code
func (o *RebootVMAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this reboot Vm accepted response has a 5xx status code
func (o *RebootVMAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this reboot Vm accepted response a status code equal to that given
func (o *RebootVMAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the reboot Vm accepted response
func (o *RebootVMAccepted) Code() int {
	return 202
}

func (o *RebootVMAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}][%d] rebootVmAccepted %s", 202, payload)
}

func (o *RebootVMAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}][%d] rebootVmAccepted %s", 202, payload)
}

func (o *RebootVMAccepted) GetPayload() *RebootVMAcceptedBody {
	return o.Payload
}

func (o *RebootVMAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(RebootVMAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRebootVMBadRequest creates a RebootVMBadRequest with default headers values
func NewRebootVMBadRequest() *RebootVMBadRequest {
	return &RebootVMBadRequest{}
}

/*
RebootVMBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type RebootVMBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this reboot Vm bad request response has a 2xx status code
func (o *RebootVMBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this reboot Vm bad request response has a 3xx status code
func (o *RebootVMBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this reboot Vm bad request response has a 4xx status code
func (o *RebootVMBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this reboot Vm bad request response has a 5xx status code
func (o *RebootVMBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this reboot Vm bad request response a status code equal to that given
func (o *RebootVMBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the reboot Vm bad request response
func (o *RebootVMBadRequest) Code() int {
	return 400
}

func (o *RebootVMBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}][%d] rebootVmBadRequest %s", 400, payload)
}

func (o *RebootVMBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}][%d] rebootVmBadRequest %s", 400, payload)
}

func (o *RebootVMBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *RebootVMBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
RebootVMAcceptedBody reboot VM accepted body
swagger:model RebootVMAcceptedBody
*/
type RebootVMAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this reboot VM accepted body
func (o *RebootVMAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RebootVMAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("rebootVmAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var rebootVmAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		rebootVmAcceptedBodyTypeStatusPropEnum = append(rebootVmAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// RebootVMAcceptedBodyStatusAccepted captures enum value "accepted"
	RebootVMAcceptedBodyStatusAccepted string = "accepted"

	// RebootVMAcceptedBodyStatusCompleted captures enum value "completed"
	RebootVMAcceptedBodyStatusCompleted string = "completed"

	// RebootVMAcceptedBodyStatusFailed captures enum value "failed"
	RebootVMAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *RebootVMAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, rebootVmAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *RebootVMAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("rebootVmAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *RebootVMAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("rebootVmAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this reboot VM accepted body based on context it is used
func (o *RebootVMAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *RebootVMAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RebootVMAcceptedBody) UnmarshalBinary(b []byte) error {
	var res RebootVMAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
