// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveCompositeFromRoleParams creates a new RemoveCompositeFromRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveCompositeFromRoleParams() *RemoveCompositeFromRoleParams {
	return NewRemoveCompositeFromRoleParamsWithTimeout(cr.DefaultTimeout)
}

// NewRemoveCompositeFromRoleParamsWithTimeout creates a new RemoveCompositeFromRoleParams object
// with the ability to set a timeout on a request.
func NewRemoveCompositeFromRoleParamsWithTimeout(timeout time.Duration) *RemoveCompositeFromRoleParams {
	return &RemoveCompositeFromRoleParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewRemoveCompositeFromRoleParamsWithContext creates a new RemoveCompositeFromRoleParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [RemoveCompositeFromRoleParams].
func NewRemoveCompositeFromRoleParamsWithContext(ctx context.Context) *RemoveCompositeFromRoleParams {
	return &RemoveCompositeFromRoleParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewRemoveCompositeFromRoleParamsWithHTTPClient creates a new RemoveCompositeFromRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveCompositeFromRoleParamsWithHTTPClient(client *http.Client) *RemoveCompositeFromRoleParams {
	return &RemoveCompositeFromRoleParams{
		HTTPClient: client,
	}
}

/*
RemoveCompositeFromRoleParams contains all the parameters to send to the API endpoint

	for the remove composite from role operation.

	Typically these are written to a http.Request.
*/
type RemoveCompositeFromRoleParams struct {

	/* ExcludeRole.

	   Name of the composed role to remove. Can be specified multiple times. (Required, at least one)
	*/
	ExcludeRole string

	/* Role.

	   Name of the composite role to update. (Required)
	*/
	Role string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the remove composite from role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveCompositeFromRoleParams) WithDefaults() *RemoveCompositeFromRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove composite from role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveCompositeFromRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) WithTimeout(timeout time.Duration) *RemoveCompositeFromRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the remove composite from role params.
//
// Deprecated: use the operation call with context to pass the context instead of [RemoveCompositeFromRoleParams].
func (o *RemoveCompositeFromRoleParams) WithContext(ctx context.Context) *RemoveCompositeFromRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove composite from role params.
//
// Deprecated: use the operation call with context to pass the context instead of [RemoveCompositeFromRoleParams].
func (o *RemoveCompositeFromRoleParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) WithHTTPClient(client *http.Client) *RemoveCompositeFromRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExcludeRole adds the excludeRole to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) WithExcludeRole(excludeRole string) *RemoveCompositeFromRoleParams {
	o.SetExcludeRole(excludeRole)
	return o
}

// SetExcludeRole adds the excludeRole to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) SetExcludeRole(excludeRole string) {
	o.ExcludeRole = excludeRole
}

// WithRole adds the role to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) WithRole(role string) *RemoveCompositeFromRoleParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the remove composite from role params.
func (o *RemoveCompositeFromRoleParams) SetRole(role string) {
	o.Role = role
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *RemoveCompositeFromRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// query param exclude-role
	qrExcludeRole := o.ExcludeRole
	qExcludeRole := qrExcludeRole
	if qExcludeRole != "" {

		if err := r.SetQueryParam("exclude-role", qExcludeRole); err != nil {
			return err
		}
	}

	// path param role
	if err := r.SetPathParam("role", o.Role); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
