// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewResizeVolumeParams creates a new ResizeVolumeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResizeVolumeParams() *ResizeVolumeParams {
	return NewResizeVolumeParamsWithTimeout(cr.DefaultTimeout)
}

// NewResizeVolumeParamsWithTimeout creates a new ResizeVolumeParams object
// with the ability to set a timeout on a request.
func NewResizeVolumeParamsWithTimeout(timeout time.Duration) *ResizeVolumeParams {
	return &ResizeVolumeParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewResizeVolumeParamsWithContext creates a new ResizeVolumeParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ResizeVolumeParams].
func NewResizeVolumeParamsWithContext(ctx context.Context) *ResizeVolumeParams {
	return &ResizeVolumeParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewResizeVolumeParamsWithHTTPClient creates a new ResizeVolumeParams object
// with the ability to set a custom HTTPClient for a request.
func NewResizeVolumeParamsWithHTTPClient(client *http.Client) *ResizeVolumeParams {
	return &ResizeVolumeParams{
		HTTPClient: client,
	}
}

/*
ResizeVolumeParams contains all the parameters to send to the API endpoint

	for the resize volume operation.

	Typically these are written to a http.Request.
*/
type ResizeVolumeParams struct {

	/* NewSize.

	   New size of the volume in GB.
	*/
	NewSize int64

	/* VolumeID.

	   Unique ID of the volume to resize.
	*/
	VolumeID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the resize volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResizeVolumeParams) WithDefaults() *ResizeVolumeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resize volume params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResizeVolumeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resize volume params.
func (o *ResizeVolumeParams) WithTimeout(timeout time.Duration) *ResizeVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resize volume params.
func (o *ResizeVolumeParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the resize volume params.
//
// Deprecated: use the operation call with context to pass the context instead of [ResizeVolumeParams].
func (o *ResizeVolumeParams) WithContext(ctx context.Context) *ResizeVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resize volume params.
//
// Deprecated: use the operation call with context to pass the context instead of [ResizeVolumeParams].
func (o *ResizeVolumeParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the resize volume params.
func (o *ResizeVolumeParams) WithHTTPClient(client *http.Client) *ResizeVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resize volume params.
func (o *ResizeVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNewSize adds the newSize to the resize volume params.
func (o *ResizeVolumeParams) WithNewSize(newSize int64) *ResizeVolumeParams {
	o.SetNewSize(newSize)
	return o
}

// SetNewSize adds the newSize to the resize volume params.
func (o *ResizeVolumeParams) SetNewSize(newSize int64) {
	o.NewSize = newSize
}

// WithVolumeID adds the volumeID to the resize volume params.
func (o *ResizeVolumeParams) WithVolumeID(volumeID string) *ResizeVolumeParams {
	o.SetVolumeID(volumeID)
	return o
}

// SetVolumeID adds the volumeId to the resize volume params.
func (o *ResizeVolumeParams) SetVolumeID(volumeID string) {
	o.VolumeID = volumeID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ResizeVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// query param new-size
	qrNewSize := o.NewSize
	qNewSize := conv.FormatInteger(qrNewSize)
	if qNewSize != "" {

		if err := r.SetQueryParam("new-size", qNewSize); err != nil {
			return err
		}
	}

	// path param volume-id
	if err := r.SetPathParam("volume-id", o.VolumeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
