// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// ShutdownVMReader is a Reader for the ShutdownVM structure.
type ShutdownVMReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShutdownVMReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewShutdownVMAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewShutdownVMBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /compute/vms/{instance-id}/shutdown] shutdownVm", response, response.Code())
	}
}

// NewShutdownVMAccepted creates a ShutdownVMAccepted with default headers values
func NewShutdownVMAccepted() *ShutdownVMAccepted {
	return &ShutdownVMAccepted{}
}

/*
ShutdownVMAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for VM shutdown
*/
type ShutdownVMAccepted struct {
	Payload *ShutdownVMAcceptedBody
}

// IsSuccess returns true when this shutdown Vm accepted response has a 2xx status code
func (o *ShutdownVMAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this shutdown Vm accepted response has a 3xx status code
func (o *ShutdownVMAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this shutdown Vm accepted response has a 4xx status code
func (o *ShutdownVMAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this shutdown Vm accepted response has a 5xx status code
func (o *ShutdownVMAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this shutdown Vm accepted response a status code equal to that given
func (o *ShutdownVMAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the shutdown Vm accepted response
func (o *ShutdownVMAccepted) Code() int {
	return 202
}

func (o *ShutdownVMAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}/shutdown][%d] shutdownVmAccepted %s", 202, payload)
}

func (o *ShutdownVMAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}/shutdown][%d] shutdownVmAccepted %s", 202, payload)
}

func (o *ShutdownVMAccepted) GetPayload() *ShutdownVMAcceptedBody {
	return o.Payload
}

func (o *ShutdownVMAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ShutdownVMAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewShutdownVMBadRequest creates a ShutdownVMBadRequest with default headers values
func NewShutdownVMBadRequest() *ShutdownVMBadRequest {
	return &ShutdownVMBadRequest{}
}

/*
ShutdownVMBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type ShutdownVMBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this shutdown Vm bad request response has a 2xx status code
func (o *ShutdownVMBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this shutdown Vm bad request response has a 3xx status code
func (o *ShutdownVMBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this shutdown Vm bad request response has a 4xx status code
func (o *ShutdownVMBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this shutdown Vm bad request response has a 5xx status code
func (o *ShutdownVMBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this shutdown Vm bad request response a status code equal to that given
func (o *ShutdownVMBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the shutdown Vm bad request response
func (o *ShutdownVMBadRequest) Code() int {
	return 400
}

func (o *ShutdownVMBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}/shutdown][%d] shutdownVmBadRequest %s", 400, payload)
}

func (o *ShutdownVMBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /compute/vms/{instance-id}/shutdown][%d] shutdownVmBadRequest %s", 400, payload)
}

func (o *ShutdownVMBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ShutdownVMBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
ShutdownVMAcceptedBody shutdown VM accepted body
swagger:model ShutdownVMAcceptedBody
*/
type ShutdownVMAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this shutdown VM accepted body
func (o *ShutdownVMAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ShutdownVMAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("shutdownVmAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var shutdownVmAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		shutdownVmAcceptedBodyTypeStatusPropEnum = append(shutdownVmAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// ShutdownVMAcceptedBodyStatusAccepted captures enum value "accepted"
	ShutdownVMAcceptedBodyStatusAccepted string = "accepted"

	// ShutdownVMAcceptedBodyStatusCompleted captures enum value "completed"
	ShutdownVMAcceptedBodyStatusCompleted string = "completed"

	// ShutdownVMAcceptedBodyStatusFailed captures enum value "failed"
	ShutdownVMAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *ShutdownVMAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, shutdownVmAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *ShutdownVMAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("shutdownVmAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *ShutdownVMAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("shutdownVmAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this shutdown VM accepted body based on context it is used
func (o *ShutdownVMAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ShutdownVMAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ShutdownVMAcceptedBody) UnmarshalBinary(b []byte) error {
	var res ShutdownVMAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
