// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopVMParams creates a new StopVMParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopVMParams() *StopVMParams {
	return NewStopVMParamsWithTimeout(cr.DefaultTimeout)
}

// NewStopVMParamsWithTimeout creates a new StopVMParams object
// with the ability to set a timeout on a request.
func NewStopVMParamsWithTimeout(timeout time.Duration) *StopVMParams {
	return &StopVMParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewStopVMParamsWithContext creates a new StopVMParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [StopVMParams].
func NewStopVMParamsWithContext(ctx context.Context) *StopVMParams {
	return &StopVMParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewStopVMParamsWithHTTPClient creates a new StopVMParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopVMParamsWithHTTPClient(client *http.Client) *StopVMParams {
	return &StopVMParams{
		HTTPClient: client,
	}
}

/*
StopVMParams contains all the parameters to send to the API endpoint

	for the stop Vm operation.

	Typically these are written to a http.Request.
*/
type StopVMParams struct {

	/* InstanceID.

	   Specify the unique instance ID of the virtual machine. This identifier is essential to locate and command the specific machine you wish to stop. (Required)
	*/
	InstanceID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the stop Vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopVMParams) WithDefaults() *StopVMParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop Vm params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopVMParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop Vm params.
func (o *StopVMParams) WithTimeout(timeout time.Duration) *StopVMParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop Vm params.
func (o *StopVMParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the stop Vm params.
//
// Deprecated: use the operation call with context to pass the context instead of [StopVMParams].
func (o *StopVMParams) WithContext(ctx context.Context) *StopVMParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop Vm params.
//
// Deprecated: use the operation call with context to pass the context instead of [StopVMParams].
func (o *StopVMParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the stop Vm params.
func (o *StopVMParams) WithHTTPClient(client *http.Client) *StopVMParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop Vm params.
func (o *StopVMParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceID adds the instanceID to the stop Vm params.
func (o *StopVMParams) WithInstanceID(instanceID string) *StopVMParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the stop Vm params.
func (o *StopVMParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *StopVMParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param instance-id
	if err := r.SetPathParam("instance-id", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
