// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// TenantNetsetReader is a Reader for the TenantNetset structure.
type TenantNetsetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantNetsetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTenantNetsetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTenantNetsetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /tenants/network/{tenant-id}] tenantNetset", response, response.Code())
	}
}

// NewTenantNetsetOK creates a TenantNetsetOK with default headers values
func NewTenantNetsetOK() *TenantNetsetOK {
	return &TenantNetsetOK{}
}

/*
TenantNetsetOK describes a response with status code 200, with default header values.

Successful response
*/
type TenantNetsetOK struct {
	Payload *TenantNetsetOKBody
}

// IsSuccess returns true when this tenant netset o k response has a 2xx status code
func (o *TenantNetsetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this tenant netset o k response has a 3xx status code
func (o *TenantNetsetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant netset o k response has a 4xx status code
func (o *TenantNetsetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this tenant netset o k response has a 5xx status code
func (o *TenantNetsetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant netset o k response a status code equal to that given
func (o *TenantNetsetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the tenant netset o k response
func (o *TenantNetsetOK) Code() int {
	return 200
}

func (o *TenantNetsetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/network/{tenant-id}][%d] tenantNetsetOK %s", 200, payload)
}

func (o *TenantNetsetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/network/{tenant-id}][%d] tenantNetsetOK %s", 200, payload)
}

func (o *TenantNetsetOK) GetPayload() *TenantNetsetOKBody {
	return o.Payload
}

func (o *TenantNetsetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(TenantNetsetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTenantNetsetBadRequest creates a TenantNetsetBadRequest with default headers values
func NewTenantNetsetBadRequest() *TenantNetsetBadRequest {
	return &TenantNetsetBadRequest{}
}

/*
TenantNetsetBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type TenantNetsetBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this tenant netset bad request response has a 2xx status code
func (o *TenantNetsetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this tenant netset bad request response has a 3xx status code
func (o *TenantNetsetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant netset bad request response has a 4xx status code
func (o *TenantNetsetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this tenant netset bad request response has a 5xx status code
func (o *TenantNetsetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant netset bad request response a status code equal to that given
func (o *TenantNetsetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the tenant netset bad request response
func (o *TenantNetsetBadRequest) Code() int {
	return 400
}

func (o *TenantNetsetBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/network/{tenant-id}][%d] tenantNetsetBadRequest %s", 400, payload)
}

func (o *TenantNetsetBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/network/{tenant-id}][%d] tenantNetsetBadRequest %s", 400, payload)
}

func (o *TenantNetsetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *TenantNetsetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
TenantNetsetOKBody tenant netset o k body
swagger:model TenantNetsetOKBody
*/
type TenantNetsetOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this tenant netset o k body
func (o *TenantNetsetOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tenant netset o k body based on context it is used
func (o *TenantNetsetOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TenantNetsetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TenantNetsetOKBody) UnmarshalBinary(b []byte) error {
	var res TenantNetsetOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
