// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTenantNetunsetParams creates a new TenantNetunsetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTenantNetunsetParams() *TenantNetunsetParams {
	return NewTenantNetunsetParamsWithTimeout(cr.DefaultTimeout)
}

// NewTenantNetunsetParamsWithTimeout creates a new TenantNetunsetParams object
// with the ability to set a timeout on a request.
func NewTenantNetunsetParamsWithTimeout(timeout time.Duration) *TenantNetunsetParams {
	return &TenantNetunsetParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewTenantNetunsetParamsWithContext creates a new TenantNetunsetParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [TenantNetunsetParams].
func NewTenantNetunsetParamsWithContext(ctx context.Context) *TenantNetunsetParams {
	return &TenantNetunsetParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewTenantNetunsetParamsWithHTTPClient creates a new TenantNetunsetParams object
// with the ability to set a custom HTTPClient for a request.
func NewTenantNetunsetParamsWithHTTPClient(client *http.Client) *TenantNetunsetParams {
	return &TenantNetunsetParams{
		HTTPClient: client,
	}
}

/*
TenantNetunsetParams contains all the parameters to send to the API endpoint

	for the tenant netunset operation.

	Typically these are written to a http.Request.
*/
type TenantNetunsetParams struct {

	/* Network.

	   Parameter network (string)
	*/
	Network *string

	/* TenantID.

	   Parameter tenantID (string)
	*/
	TenantID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the tenant netunset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TenantNetunsetParams) WithDefaults() *TenantNetunsetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tenant netunset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TenantNetunsetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tenant netunset params.
func (o *TenantNetunsetParams) WithTimeout(timeout time.Duration) *TenantNetunsetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tenant netunset params.
func (o *TenantNetunsetParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the tenant netunset params.
//
// Deprecated: use the operation call with context to pass the context instead of [TenantNetunsetParams].
func (o *TenantNetunsetParams) WithContext(ctx context.Context) *TenantNetunsetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tenant netunset params.
//
// Deprecated: use the operation call with context to pass the context instead of [TenantNetunsetParams].
func (o *TenantNetunsetParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the tenant netunset params.
func (o *TenantNetunsetParams) WithHTTPClient(client *http.Client) *TenantNetunsetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tenant netunset params.
func (o *TenantNetunsetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetwork adds the network to the tenant netunset params.
func (o *TenantNetunsetParams) WithNetwork(network *string) *TenantNetunsetParams {
	o.SetNetwork(network)
	return o
}

// SetNetwork adds the network to the tenant netunset params.
func (o *TenantNetunsetParams) SetNetwork(network *string) {
	o.Network = network
}

// WithTenantID adds the tenantID to the tenant netunset params.
func (o *TenantNetunsetParams) WithTenantID(tenantID string) *TenantNetunsetParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the tenant netunset params.
func (o *TenantNetunsetParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *TenantNetunsetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.Network != nil {

		// query param network
		var qrNetwork string

		if o.Network != nil {
			qrNetwork = *o.Network
		}
		qNetwork := qrNetwork
		if qNetwork != "" {

			if err := r.SetQueryParam("network", qNetwork); err != nil {
				return err
			}
		}
	}

	// path param tenant-id
	if err := r.SetPathParam("tenant-id", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
