// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// TenantImagelistReader is a Reader for the TenantImagelist structure.
type TenantImagelistReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantImagelistReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTenantImagelistOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTenantImagelistBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tenants/image/{tenant-id}] tenantImagelist", response, response.Code())
	}
}

// NewTenantImagelistOK creates a TenantImagelistOK with default headers values
func NewTenantImagelistOK() *TenantImagelistOK {
	return &TenantImagelistOK{}
}

/*
TenantImagelistOK describes a response with status code 200, with default header values.

Successful response
*/
type TenantImagelistOK struct {
	Payload []*TenantImagelistOKBodyItems0
}

// IsSuccess returns true when this tenant imagelist o k response has a 2xx status code
func (o *TenantImagelistOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this tenant imagelist o k response has a 3xx status code
func (o *TenantImagelistOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant imagelist o k response has a 4xx status code
func (o *TenantImagelistOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this tenant imagelist o k response has a 5xx status code
func (o *TenantImagelistOK) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant imagelist o k response a status code equal to that given
func (o *TenantImagelistOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the tenant imagelist o k response
func (o *TenantImagelistOK) Code() int {
	return 200
}

func (o *TenantImagelistOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/image/{tenant-id}][%d] tenantImagelistOK %s", 200, payload)
}

func (o *TenantImagelistOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/image/{tenant-id}][%d] tenantImagelistOK %s", 200, payload)
}

func (o *TenantImagelistOK) GetPayload() []*TenantImagelistOKBodyItems0 {
	return o.Payload
}

func (o *TenantImagelistOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTenantImagelistBadRequest creates a TenantImagelistBadRequest with default headers values
func NewTenantImagelistBadRequest() *TenantImagelistBadRequest {
	return &TenantImagelistBadRequest{}
}

/*
TenantImagelistBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type TenantImagelistBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this tenant imagelist bad request response has a 2xx status code
func (o *TenantImagelistBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this tenant imagelist bad request response has a 3xx status code
func (o *TenantImagelistBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant imagelist bad request response has a 4xx status code
func (o *TenantImagelistBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this tenant imagelist bad request response has a 5xx status code
func (o *TenantImagelistBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant imagelist bad request response a status code equal to that given
func (o *TenantImagelistBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the tenant imagelist bad request response
func (o *TenantImagelistBadRequest) Code() int {
	return 400
}

func (o *TenantImagelistBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/image/{tenant-id}][%d] tenantImagelistBadRequest %s", 400, payload)
}

func (o *TenantImagelistBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tenants/image/{tenant-id}][%d] tenantImagelistBadRequest %s", 400, payload)
}

func (o *TenantImagelistBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *TenantImagelistBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
TenantImagelistOKBodyItems0 tenant imagelist o k body items0
swagger:model TenantImagelistOKBodyItems0
*/
type TenantImagelistOKBodyItems0 struct {

	// Name of the tenant backend image
	BackendName string `json:"backend-name,omitempty"`

	// Name of the tenant image
	Name string `json:"name,omitempty"`
}

// Validate validates this tenant imagelist o k body items0
func (o *TenantImagelistOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tenant imagelist o k body items0 based on context it is used
func (o *TenantImagelistOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TenantImagelistOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TenantImagelistOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res TenantImagelistOKBodyItems0
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
