// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// TenantImagesetReader is a Reader for the TenantImageset structure.
type TenantImagesetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenantImagesetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTenantImagesetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTenantImagesetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /tenants/image/{tenant-id}] tenantImageset", response, response.Code())
	}
}

// NewTenantImagesetOK creates a TenantImagesetOK with default headers values
func NewTenantImagesetOK() *TenantImagesetOK {
	return &TenantImagesetOK{}
}

/*
TenantImagesetOK describes a response with status code 200, with default header values.

Successful response
*/
type TenantImagesetOK struct {
	Payload *TenantImagesetOKBody
}

// IsSuccess returns true when this tenant imageset o k response has a 2xx status code
func (o *TenantImagesetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this tenant imageset o k response has a 3xx status code
func (o *TenantImagesetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant imageset o k response has a 4xx status code
func (o *TenantImagesetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this tenant imageset o k response has a 5xx status code
func (o *TenantImagesetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant imageset o k response a status code equal to that given
func (o *TenantImagesetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the tenant imageset o k response
func (o *TenantImagesetOK) Code() int {
	return 200
}

func (o *TenantImagesetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/image/{tenant-id}][%d] tenantImagesetOK %s", 200, payload)
}

func (o *TenantImagesetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/image/{tenant-id}][%d] tenantImagesetOK %s", 200, payload)
}

func (o *TenantImagesetOK) GetPayload() *TenantImagesetOKBody {
	return o.Payload
}

func (o *TenantImagesetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(TenantImagesetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTenantImagesetBadRequest creates a TenantImagesetBadRequest with default headers values
func NewTenantImagesetBadRequest() *TenantImagesetBadRequest {
	return &TenantImagesetBadRequest{}
}

/*
TenantImagesetBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type TenantImagesetBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this tenant imageset bad request response has a 2xx status code
func (o *TenantImagesetBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this tenant imageset bad request response has a 3xx status code
func (o *TenantImagesetBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenant imageset bad request response has a 4xx status code
func (o *TenantImagesetBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this tenant imageset bad request response has a 5xx status code
func (o *TenantImagesetBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this tenant imageset bad request response a status code equal to that given
func (o *TenantImagesetBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the tenant imageset bad request response
func (o *TenantImagesetBadRequest) Code() int {
	return 400
}

func (o *TenantImagesetBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/image/{tenant-id}][%d] tenantImagesetBadRequest %s", 400, payload)
}

func (o *TenantImagesetBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tenants/image/{tenant-id}][%d] tenantImagesetBadRequest %s", 400, payload)
}

func (o *TenantImagesetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *TenantImagesetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
TenantImagesetOKBody tenant imageset o k body
swagger:model TenantImagesetOKBody
*/
type TenantImagesetOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this tenant imageset o k body
func (o *TenantImagesetOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tenant imageset o k body based on context it is used
func (o *TenantImagesetOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TenantImagesetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TenantImagesetOKBody) UnmarshalBinary(b []byte) error {
	var res TenantImagesetOKBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
