// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// UnlockUserReader is a Reader for the UnlockUser structure.
type UnlockUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlockUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewUnlockUserAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnlockUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUnlockUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUnlockUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /users/{user-id}/unlock] unlockUser", response, response.Code())
	}
}

// NewUnlockUserAccepted creates a UnlockUserAccepted with default headers values
func NewUnlockUserAccepted() *UnlockUserAccepted {
	return &UnlockUserAccepted{}
}

/*
UnlockUserAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for user account unlock
*/
type UnlockUserAccepted struct {
	Payload *UnlockUserAcceptedBody
}

// IsSuccess returns true when this unlock user accepted response has a 2xx status code
func (o *UnlockUserAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unlock user accepted response has a 3xx status code
func (o *UnlockUserAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock user accepted response has a 4xx status code
func (o *UnlockUserAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this unlock user accepted response has a 5xx status code
func (o *UnlockUserAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this unlock user accepted response a status code equal to that given
func (o *UnlockUserAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the unlock user accepted response
func (o *UnlockUserAccepted) Code() int {
	return 202
}

func (o *UnlockUserAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserAccepted %s", 202, payload)
}

func (o *UnlockUserAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserAccepted %s", 202, payload)
}

func (o *UnlockUserAccepted) GetPayload() *UnlockUserAcceptedBody {
	return o.Payload
}

func (o *UnlockUserAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UnlockUserAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUnlockUserBadRequest creates a UnlockUserBadRequest with default headers values
func NewUnlockUserBadRequest() *UnlockUserBadRequest {
	return &UnlockUserBadRequest{}
}

/*
UnlockUserBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type UnlockUserBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this unlock user bad request response has a 2xx status code
func (o *UnlockUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unlock user bad request response has a 3xx status code
func (o *UnlockUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock user bad request response has a 4xx status code
func (o *UnlockUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this unlock user bad request response has a 5xx status code
func (o *UnlockUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this unlock user bad request response a status code equal to that given
func (o *UnlockUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the unlock user bad request response
func (o *UnlockUserBadRequest) Code() int {
	return 400
}

func (o *UnlockUserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserBadRequest %s", 400, payload)
}

func (o *UnlockUserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserBadRequest %s", 400, payload)
}

func (o *UnlockUserBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnlockUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUnlockUserUnauthorized creates a UnlockUserUnauthorized with default headers values
func NewUnlockUserUnauthorized() *UnlockUserUnauthorized {
	return &UnlockUserUnauthorized{}
}

/*
UnlockUserUnauthorized describes a response with status code 401, with default header values.

Incorrect username or password.
*/
type UnlockUserUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this unlock user unauthorized response has a 2xx status code
func (o *UnlockUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unlock user unauthorized response has a 3xx status code
func (o *UnlockUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock user unauthorized response has a 4xx status code
func (o *UnlockUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this unlock user unauthorized response has a 5xx status code
func (o *UnlockUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this unlock user unauthorized response a status code equal to that given
func (o *UnlockUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the unlock user unauthorized response
func (o *UnlockUserUnauthorized) Code() int {
	return 401
}

func (o *UnlockUserUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserUnauthorized %s", 401, payload)
}

func (o *UnlockUserUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserUnauthorized %s", 401, payload)
}

func (o *UnlockUserUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnlockUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUnlockUserInternalServerError creates a UnlockUserInternalServerError with default headers values
func NewUnlockUserInternalServerError() *UnlockUserInternalServerError {
	return &UnlockUserInternalServerError{}
}

/*
UnlockUserInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type UnlockUserInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this unlock user internal server error response has a 2xx status code
func (o *UnlockUserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unlock user internal server error response has a 3xx status code
func (o *UnlockUserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock user internal server error response has a 4xx status code
func (o *UnlockUserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this unlock user internal server error response has a 5xx status code
func (o *UnlockUserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this unlock user internal server error response a status code equal to that given
func (o *UnlockUserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the unlock user internal server error response
func (o *UnlockUserInternalServerError) Code() int {
	return 500
}

func (o *UnlockUserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserInternalServerError %s", 500, payload)
}

func (o *UnlockUserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /users/{user-id}/unlock][%d] unlockUserInternalServerError %s", 500, payload)
}

func (o *UnlockUserInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnlockUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
UnlockUserAcceptedBody unlock user accepted body
swagger:model UnlockUserAcceptedBody
*/
type UnlockUserAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this unlock user accepted body
func (o *UnlockUserAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UnlockUserAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("unlockUserAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var unlockUserAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		unlockUserAcceptedBodyTypeStatusPropEnum = append(unlockUserAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// UnlockUserAcceptedBodyStatusAccepted captures enum value "accepted"
	UnlockUserAcceptedBodyStatusAccepted string = "accepted"

	// UnlockUserAcceptedBodyStatusCompleted captures enum value "completed"
	UnlockUserAcceptedBodyStatusCompleted string = "completed"

	// UnlockUserAcceptedBodyStatusFailed captures enum value "failed"
	UnlockUserAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *UnlockUserAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, unlockUserAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UnlockUserAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("unlockUserAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *UnlockUserAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("unlockUserAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this unlock user accepted body based on context it is used
func (o *UnlockUserAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UnlockUserAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UnlockUserAcceptedBody) UnmarshalBinary(b []byte) error {
	var res UnlockUserAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
