// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
	"github.com/welibekov/ptc-csi-driver/pkg/ptc/client/models"
)

// UnlockTenantReader is a Reader for the UnlockTenant structure.
type UnlockTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlockTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 202:
		result := NewUnlockTenantAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnlockTenantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /tenants/{tenant-id}/unlock] unlockTenant", response, response.Code())
	}
}

// NewUnlockTenantAccepted creates a UnlockTenantAccepted with default headers values
func NewUnlockTenantAccepted() *UnlockTenantAccepted {
	return &UnlockTenantAccepted{}
}

/*
UnlockTenantAccepted describes a response with status code 202, with default header values.

Asynchronous request accepted for tenant unlock
*/
type UnlockTenantAccepted struct {
	Payload *UnlockTenantAcceptedBody
}

// IsSuccess returns true when this unlock tenant accepted response has a 2xx status code
func (o *UnlockTenantAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unlock tenant accepted response has a 3xx status code
func (o *UnlockTenantAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock tenant accepted response has a 4xx status code
func (o *UnlockTenantAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this unlock tenant accepted response has a 5xx status code
func (o *UnlockTenantAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this unlock tenant accepted response a status code equal to that given
func (o *UnlockTenantAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the unlock tenant accepted response
func (o *UnlockTenantAccepted) Code() int {
	return 202
}

func (o *UnlockTenantAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenants/{tenant-id}/unlock][%d] unlockTenantAccepted %s", 202, payload)
}

func (o *UnlockTenantAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenants/{tenant-id}/unlock][%d] unlockTenantAccepted %s", 202, payload)
}

func (o *UnlockTenantAccepted) GetPayload() *UnlockTenantAcceptedBody {
	return o.Payload
}

func (o *UnlockTenantAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UnlockTenantAcceptedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUnlockTenantBadRequest creates a UnlockTenantBadRequest with default headers values
func NewUnlockTenantBadRequest() *UnlockTenantBadRequest {
	return &UnlockTenantBadRequest{}
}

/*
UnlockTenantBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type UnlockTenantBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this unlock tenant bad request response has a 2xx status code
func (o *UnlockTenantBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unlock tenant bad request response has a 3xx status code
func (o *UnlockTenantBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unlock tenant bad request response has a 4xx status code
func (o *UnlockTenantBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this unlock tenant bad request response has a 5xx status code
func (o *UnlockTenantBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this unlock tenant bad request response a status code equal to that given
func (o *UnlockTenantBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the unlock tenant bad request response
func (o *UnlockTenantBadRequest) Code() int {
	return 400
}

func (o *UnlockTenantBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenants/{tenant-id}/unlock][%d] unlockTenantBadRequest %s", 400, payload)
}

func (o *UnlockTenantBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenants/{tenant-id}/unlock][%d] unlockTenantBadRequest %s", 400, payload)
}

func (o *UnlockTenantBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnlockTenantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
UnlockTenantAcceptedBody unlock tenant accepted body
swagger:model UnlockTenantAcceptedBody
*/
type UnlockTenantAcceptedBody struct {

	// Task created timestamp
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// Detailed error message if the task failed
	ErrorDescription string `json:"error-description,omitempty"`

	// Current status of the task
	// Enum: ["accepted","completed","failed"]
	Status string `json:"status,omitempty"`

	// Unique identifier for tracking the asynchronous task
	TaskID string `json:"task-id,omitempty"`

	// Task updated timestamp
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this unlock tenant accepted body
func (o *UnlockTenantAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UnlockTenantAcceptedBody) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("unlockTenantAccepted"+"."+"created_at", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var unlockTenantAcceptedBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["accepted","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		unlockTenantAcceptedBodyTypeStatusPropEnum = append(unlockTenantAcceptedBodyTypeStatusPropEnum, v)
	}
}

const (

	// UnlockTenantAcceptedBodyStatusAccepted captures enum value "accepted"
	UnlockTenantAcceptedBodyStatusAccepted string = "accepted"

	// UnlockTenantAcceptedBodyStatusCompleted captures enum value "completed"
	UnlockTenantAcceptedBodyStatusCompleted string = "completed"

	// UnlockTenantAcceptedBodyStatusFailed captures enum value "failed"
	UnlockTenantAcceptedBodyStatusFailed string = "failed"
)

// prop value enum
func (o *UnlockTenantAcceptedBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, unlockTenantAcceptedBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UnlockTenantAcceptedBody) validateStatus(formats strfmt.Registry) error {
	if typeutils.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("unlockTenantAccepted"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *UnlockTenantAcceptedBody) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("unlockTenantAccepted"+"."+"updated_at", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this unlock tenant accepted body based on context it is used
func (o *UnlockTenantAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UnlockTenantAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UnlockTenantAcceptedBody) UnmarshalBinary(b []byte) error {
	var res UnlockTenantAcceptedBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
