// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateRoleParams creates a new UpdateRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRoleParams() *UpdateRoleParams {
	return NewUpdateRoleParamsWithTimeout(cr.DefaultTimeout)
}

// NewUpdateRoleParamsWithTimeout creates a new UpdateRoleParams object
// with the ability to set a timeout on a request.
func NewUpdateRoleParamsWithTimeout(timeout time.Duration) *UpdateRoleParams {
	return &UpdateRoleParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewUpdateRoleParamsWithContext creates a new UpdateRoleParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateRoleParams].
func NewUpdateRoleParamsWithContext(ctx context.Context) *UpdateRoleParams {
	return &UpdateRoleParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewUpdateRoleParamsWithHTTPClient creates a new UpdateRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRoleParamsWithHTTPClient(client *http.Client) *UpdateRoleParams {
	return &UpdateRoleParams{
		HTTPClient: client,
	}
}

/*
UpdateRoleParams contains all the parameters to send to the API endpoint

	for the update role operation.

	Typically these are written to a http.Request.
*/
type UpdateRoleParams struct {

	/* AddPermission.

	   Add a granular permission to this role. Can be specified multiple times.
	*/
	AddPermission *string

	/* Description.

	   New description of the role.
	*/
	Description *string

	/* ExcludeRole.

	   Remove a composed (nested) role from this composite role. Can be specified multiple times.
	*/
	ExcludeRole *string

	/* IncludeRole.

	   Add a composed (nested) role to this composite role. Can be specified multiple times.
	*/
	IncludeRole *string

	/* Name.

	   Current name of the role to update. (Required)
	*/
	Name string

	/* NewName.

	   New name for the role (optional). Not allowed for system roles.
	*/
	NewName *string

	/* RemovePermission.

	   Remove a granular permission from this role. Can be specified multiple times.
	*/
	RemovePermission *string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the update role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRoleParams) WithDefaults() *UpdateRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update role params.
func (o *UpdateRoleParams) WithTimeout(timeout time.Duration) *UpdateRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update role params.
func (o *UpdateRoleParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the update role params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateRoleParams].
func (o *UpdateRoleParams) WithContext(ctx context.Context) *UpdateRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update role params.
//
// Deprecated: use the operation call with context to pass the context instead of [UpdateRoleParams].
func (o *UpdateRoleParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the update role params.
func (o *UpdateRoleParams) WithHTTPClient(client *http.Client) *UpdateRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update role params.
func (o *UpdateRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddPermission adds the addPermission to the update role params.
func (o *UpdateRoleParams) WithAddPermission(addPermission *string) *UpdateRoleParams {
	o.SetAddPermission(addPermission)
	return o
}

// SetAddPermission adds the addPermission to the update role params.
func (o *UpdateRoleParams) SetAddPermission(addPermission *string) {
	o.AddPermission = addPermission
}

// WithDescription adds the description to the update role params.
func (o *UpdateRoleParams) WithDescription(description *string) *UpdateRoleParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the update role params.
func (o *UpdateRoleParams) SetDescription(description *string) {
	o.Description = description
}

// WithExcludeRole adds the excludeRole to the update role params.
func (o *UpdateRoleParams) WithExcludeRole(excludeRole *string) *UpdateRoleParams {
	o.SetExcludeRole(excludeRole)
	return o
}

// SetExcludeRole adds the excludeRole to the update role params.
func (o *UpdateRoleParams) SetExcludeRole(excludeRole *string) {
	o.ExcludeRole = excludeRole
}

// WithIncludeRole adds the includeRole to the update role params.
func (o *UpdateRoleParams) WithIncludeRole(includeRole *string) *UpdateRoleParams {
	o.SetIncludeRole(includeRole)
	return o
}

// SetIncludeRole adds the includeRole to the update role params.
func (o *UpdateRoleParams) SetIncludeRole(includeRole *string) {
	o.IncludeRole = includeRole
}

// WithName adds the name to the update role params.
func (o *UpdateRoleParams) WithName(name string) *UpdateRoleParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update role params.
func (o *UpdateRoleParams) SetName(name string) {
	o.Name = name
}

// WithNewName adds the newName to the update role params.
func (o *UpdateRoleParams) WithNewName(newName *string) *UpdateRoleParams {
	o.SetNewName(newName)
	return o
}

// SetNewName adds the newName to the update role params.
func (o *UpdateRoleParams) SetNewName(newName *string) {
	o.NewName = newName
}

// WithRemovePermission adds the removePermission to the update role params.
func (o *UpdateRoleParams) WithRemovePermission(removePermission *string) *UpdateRoleParams {
	o.SetRemovePermission(removePermission)
	return o
}

// SetRemovePermission adds the removePermission to the update role params.
func (o *UpdateRoleParams) SetRemovePermission(removePermission *string) {
	o.RemovePermission = removePermission
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *UpdateRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	if o.AddPermission != nil {

		// query param add-permission
		var qrAddPermission string

		if o.AddPermission != nil {
			qrAddPermission = *o.AddPermission
		}
		qAddPermission := qrAddPermission
		if qAddPermission != "" {

			if err := r.SetQueryParam("add-permission", qAddPermission); err != nil {
				return err
			}
		}
	}

	if o.Description != nil {

		// query param description
		var qrDescription string

		if o.Description != nil {
			qrDescription = *o.Description
		}
		qDescription := qrDescription
		if qDescription != "" {

			if err := r.SetQueryParam("description", qDescription); err != nil {
				return err
			}
		}
	}

	if o.ExcludeRole != nil {

		// query param exclude-role
		var qrExcludeRole string

		if o.ExcludeRole != nil {
			qrExcludeRole = *o.ExcludeRole
		}
		qExcludeRole := qrExcludeRole
		if qExcludeRole != "" {

			if err := r.SetQueryParam("exclude-role", qExcludeRole); err != nil {
				return err
			}
		}
	}

	if o.IncludeRole != nil {

		// query param include-role
		var qrIncludeRole string

		if o.IncludeRole != nil {
			qrIncludeRole = *o.IncludeRole
		}
		qIncludeRole := qrIncludeRole
		if qIncludeRole != "" {

			if err := r.SetQueryParam("include-role", qIncludeRole); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.NewName != nil {

		// query param new-name
		var qrNewName string

		if o.NewName != nil {
			qrNewName = *o.NewName
		}
		qNewName := qrNewName
		if qNewName != "" {

			if err := r.SetQueryParam("new-name", qNewName); err != nil {
				return err
			}
		}
	}

	if o.RemovePermission != nil {

		// query param remove-permission
		var qrRemovePermission string

		if o.RemovePermission != nil {
			qrRemovePermission = *o.RemovePermission
		}
		qRemovePermission := qrRemovePermission
		if qRemovePermission != "" {

			if err := r.SetQueryParam("remove-permission", qRemovePermission); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
